### ISSUE TITLE
“An error occurred, please try again”

### ISSUE THREAD

**Issue by xplosionmind** [Alovoa/alovoa#109]
The error in the title is the one I constantly get after almost everything I do (swiping for a match, editing my bio, searching…)

I do not get if my actions actually work or not.

**Comment by Nonononoki** [comment]
Looks like opening the PWA will sometimes not refresh the session cookie.

Added some workarounds to refresh the page when error 403 occurs in user pages:
cea8e13771dc9448ff9823f7c245eacc2fbea55b
dac792ea7fcf495e9925adfef4d12df72f4f3c1e
