### ISSUE TITLE
A Better Readme for building the app and deploying

### ISSUE THREAD

**Issue by sahin52** [Alovoa/alovoa#110]
I am new to developing Spring boot apps, and it gets really hard to deploy when you don't have enough knowledge.  

- I created a mail server in my server, I enrolled to Google Api for google.client-id, I created a Db with MariaDb, I added the details in application.properties
-  I dont know what "app.text.key" and "app.text.salt" means, I couldn't find a resource about this.
- When I run mvn install, I got lots of errors saying "Cache bucket4j already exists", and saying 
``` 
[[ERROR] encrypt  Time elapsed: 8.552 s  <<< ERROR!
java.security.InvalidKeyException: Invalid AES key length: 17 bytes
	at com.nonononoki.alovoa.runner.TextEncryptorConverterTest.encrypt(TextEncryptorConverterTest.java:42)

[[ERROR] decrypt  Time elapsed: 4.477 s  <<< ERROR!
java.security.InvalidKeyException: Invalid AES key length: 17 bytes
	at com.nonononoki.alovoa.runner.TextEncryptorConverterTest.decrypt(TextEncryptorConverterTest.java:35)``` 

- And I don't actually know how to deploy the app, It's actually my problem but I really want to see a better readme for deploying reasons, to let more people get involved in this project. There is a page for this purpose in oracle docs (https://docs.oracle.com/javase/tutorial/deployment/webstart/deploying.html) but it seems to be very complex to me 😢
- After all of this, since the mail server and the java app will be running in the same server, an example nginx configuration would be great.

**Comment by sahin52** [comment]
Thank you!! 

Can app.text.key + salt be any strings, or must they be generated or taken from somewhere?

**Comment by Nonononoki** [comment]
Key and salt can be any string I think, or at least be base64 compatible characters. Salt has a character length requirement.
