### ISSUE TITLE
Don't use browser dialogs

### ISSUE THREAD

**Issue by davidak** [Alovoa/alovoa#119]
It is very annoying and not user friendly. No modern web app works this way.

Example:

![Screenshot from 2021-11-29 21-46-27](https://user-images.githubusercontent.com/91113/143940563-5a15ae69-268b-4e2d-a1a8-03eba1c98bb8.png)

**Comment by Nonononoki** [comment]
Fixed in 506eda3de6f935ae60b8f095602082fe3000a618
