### ISSUE TITLE
Users can't be removed from search list

### ISSUE THREAD

**Issue by davidak** [Alovoa/alovoa#120]
Users disappear from the search when i approve or reject them, but when i'm not in their search criteria, i can only remove them from the list by blocking them. They should probably not be shown in the first place, since i have no chance to contact them.

This is one of the most annoying issues for me.

**Comment by Nonononoki** [comment]
It's already possible on mobile with swiping. I suggest adding keyboard navigation with arrow keys for desktop.
Left arrow: Swipe left (dislike)
Right arrow: Swipe right (like)

**Comment by Nonononoki** [comment]
Added like/dislike swiping on desktop.
