### ISSUE TITLE
Support emojis in chat 😸🍻🧨🎉

### ISSUE THREAD

**Issue by davidak** [Alovoa/alovoa#122]
most important feature lol

**Comment by Nonononoki** [comment]
Emojis are already supported. If it does not work for you please state your device model and browser/app version.

**Comment by davidak** [comment]
You are right in the sense that i can copy and paste emojis, but there is no option to insert emojis.

![Screenshot from 2021-12-04 19 04 27](https://user-images.githubusercontent.com/91113/144719896-82cc886a-088c-44d6-8caf-5e8ccb6886f6.png)

For reference: This is the emoji selector from Signal. I expect something similar!

![Screenshot from 2021-12-04 19 06 41](https://user-images.githubusercontent.com/91113/144719946-9584785e-b2a9-449f-8533-b9fb3e09ad67.png)

Device is this: https://davidak.de/uses/#workstation

Browser is Google Chrome 96.0.4664.45.

**Comment by Link2000** [comment]
Just use " Win + . " on Windows

**Comment by Nonononoki** [comment]
Frontend has moved to https://github.com/Alovoa/alovoa-expo
