### ISSUE TITLE
No user feedback when deleting account

### ISSUE THREAD

**Issue by davidak** [Alovoa/alovoa#123]
When i click delete the account, it takes 6 seconds until the success message appears. In that time a user would click the button 100 times, because there is no indication that something is happening. Add an indicator, like loading icon.

![Screenshot from 2021-12-06 00 44 56](https://user-images.githubusercontent.com/91113/144768903-c0a8adb4-2e7b-4f58-8416-fbd515dfc0f1.png)

**Comment by Nonononoki** [comment]
Fixed in 33b87739ab97e101697868ba0f0416259acb7d7d
Will be deployed soon, probably on the weekend
