### ISSUE TITLE
immediate crash, tomcat initialization failure

### ISSUE THREAD

**Issue by Apprisco** [Alovoa/alovoa#126]
https://www.toptal.com/developers/hastebin/uvehefotan.properties
Happens even with default alovoa with my own keys. Unsure as to what's happening, as it was running fine before. Sorry for pestering you, and thank you for the wonderful backend.

**Comment by Nonononoki** [comment]
Have you entered valid data in application.properties?
Uncomment (and adjust) these lines if you use a valid certificate
```
#server.ssl.key-store-type=PKCS12
#server.ssl.key-store=alovoa.p12
#server.ssl.key-store-password=alovoa
#server.ssl.key-alias=alovoa
```

**Comment by Apprisco** [comment]
Yes! Those lines are all commented out too, and I've verified that all the data is accurate in application.properties.

**Comment by Nonononoki** [comment]
Not sure where the error is, but the latest commit is a WIP and broke some stuff so you should revert that one if you are up-to-date.
Could you run `mvn clean build?

**Comment by Apprisco** [comment]
I was using the 1.1.2 official release version, so that shouldn't be an issue. Clean build didn't help either, compiling 1.1.2 right now does not pass the test either. There is something seriously wrong, maybe a dependency with unspecified version just released an update or something?

**Comment by Apprisco** [comment]
Issue fixed, I have no idea wtf I did to fix it, but it's gone. Thank you so much, holy crap, the website is being hosted too.
