### ISSUE TITLE
Change dependency of sejda imageio to fix captcha compat with arm64

### ISSUE THREAD

**Issue by Apprisco** [Alovoa/alovoa#128]
<dependency>
	<groupId>com.github.gotson</groupId>
	<artifactId>webp-imageio</artifactId>
	<version>0.2.1</version>
</dependency>

There is a PR for sejda's imageio library that allows for arm64 usage, as it uses a more cross-platform library.
Building with this instead seems to work perfectly, and captcha seems to be the only reason alovoa is not usable on arm64.
Thank you.

**Comment by Nonononoki** [comment]
Done with this commit: a3a48db98059d8d84ec446f1f44829c79acc7fac
