### ISSUE TITLE
periods not registering in email signup

### ISSUE THREAD

**Issue by Apprisco** [Alovoa/alovoa#130]
It seems that periods are being removed from email addresses such as ___.___@___.com, to ______@___.com.

**Comment by Nonononoki** [comment]
Intended for gmail addresses to prevent spam

**Comment by Apprisco** [comment]
> Intended for gmail addresses to prevent spam

Is there any way to disable this? There should be better ways to handle email addresses like this. I don't mind risking spam to enable this feature.

**Comment by Apprisco** [comment]
Ended up just specifying in the email itself.
