### ISSUE TITLE
Can't login at all

### ISSUE THREAD

**Issue by MF-Debug** [Alovoa/alovoa#132]
I can't login even after entering the password & captcha numerous times correctly. I don't know what is going wrong here. attached screenshot for reference.
![image](https://user-images.githubusercontent.com/6173607/156591950-b2e2e7af-1900-43db-8e00-5e348a593ede.png)
![image](https://user-images.githubusercontent.com/6173607/156592198-3bdc9549-b9a2-42da-93a7-e781e7e040ae.png)

**Comment by Nonononoki** [comment]
Hi, could you check if your email address is written exactly as in the emails sent to you by the system?

**Comment by MF-Debug** [comment]
weird thing I noticed after following your guide, my registered email contains a dot between the address. But Alovoa verfication email which was sent to my email shows that there was no dot between my email address! Yet I received the emails! Then I also found this interesting thing - 
![image](https://user-images.githubusercontent.com/6173607/156766736-3afcb914-ab53-407a-bed0-2e01baebc70f.png)
