### ISSUE TITLE
Error when liking users.

### ISSUE THREAD

**Issue by mruncreative** [Alovoa/alovoa#137]
It says error try again and returns HTTP 409. You can like the same users again and the same message will appear and the users don't appear in the list of liked users.
This error happens when liking some users and not for others.

**Comment by mruncreative** [comment]
The same people who can't be liked, no matter how often I try are dislikable. Is there a way to undislike people?

**Comment by Nonononoki** [comment]
You can only like users when you fit their filter, do you see the like button at the bottom?

**Comment by Nonononoki** [comment]
Dislike is just a simple hide, hidden/disliked users appear here: https://alovoa.com/user/disliked-users. Disliked users will reappear after a certain time has passed.

**Comment by mruncreative** [comment]
What filters? Distance, age? I'm fairly young. No, it shows the like button on barely anyone but you can swap anyone to the right. Why even present them, when there is absolutely NO WAY to interact with them?

**Comment by mruncreative** [comment]
Further there are no other users in a 100 km radius.

**Comment by Nonononoki** [comment]
> Further there are no other users in a 100 km radius.
Platform is still work in progress, new users come in every day. Please be patient.

> Why even present them, when there is absolutely NO WAY to interact with them?
So that it wouldn't feel so empty when looking for new users. This is intended.

**Comment by mruncreative** [comment]
>So that it wouldn't feel so empty when looking for new users. This is intended.
Hold on. You just openly admitted, you are **scamming** people!
How are people supposed to connect when there is no way to do so?
And you still didn't explain what criteria you used to keep me from liking other users who are in my own fucking country!

**Comment by Nonononoki** [comment]
> Hold on. You just openly admitted, you are scamming people!

How is that scam? You can't interact with them. It's only there for the visual aspect.

> How are people supposed to connect when there is no way to do so?

You can if you two match.

> And you still didn't explain what criteria you used to keep me from liking other users who are in my own fucking country!

Check your filters. Go to their profile and check their filters. You're able to like them if both filters match.

**Comment by mruncreative** [comment]
Ahhh. I figured it out. They are all set to: getting to know new people. Like almost every profile. I changed it from relationship to getting to know new people and now they all show the buttons.
**Problem: I can't change it back.**
It now only shows the option "getting to know new people". This is definitly a bug, isn't it?

**Comment by mruncreative** [comment]
![image](https://user-images.githubusercontent.com/67873653/158814488-d38cd0a5-827f-42c1-b94c-d18ca6383a54.png)

**Comment by mruncreative** [comment]
I don't know how those options even exclude each other.

**Comment by mruncreative** [comment]
I wish your code was written in C, so I could understand what the fuck is going on.
ProfileResource.java
userIntentionRepo.findAll()
extends JpaRepository
Wait where is jparepository that fucks it up? It worked when onboarding. And the onboarding page uses the same function.

**Comment by mruncreative** [comment]
I suspect most people are stuck on "getting to know people".

**Comment by mruncreative** [comment]
Ah, now I see. You're blocked from changing it for x hours. Why doesn't it say so anywhere?

**Comment by Nonononoki** [comment]
By default it's 24 hours. It's bugged right now after changing the default alerts to custom alerts. Will be fixed in the next update.
