### ISSUE TITLE
Allow setting gender

### ISSUE THREAD

**Issue by 12people** [Alovoa/alovoa#142]
There's a "looking for" setting for gender, but it's often impossible to tell the gender of other users, as most users right now don't have a face pic on their profile.

It'd be good to be able to set your gender on your profile (including non-binary).

**Comment by 12people** [comment]
@Nonononoki

It'd be great to have the gender written out, at the very least inside a profile. I honestly did not notice any coloring.

As for the potential of abuse, wouldn't the same type of abuse be possible just by having two different profiles?

**Comment by Nonononoki** [comment]
The gender is displayed in the users page (click on their picture).

I believe that most _casual_ abusers just don't want to deal with the hassle of maintaining multiple accounts. This is not for prevention, just a small reduction of abusers. And most people won't ever change their gender anyway, and if they do they only need to delete their account and create a new one.
