### ISSUE TITLE
Swipe is too sensitive

### ISSUE THREAD

**Issue by 12people** [Alovoa/alovoa#143]
While swipe might be nice to use on a phone, it's way too sensitive with a mouse and keyboard. On my first use, I accidentally swiped away a person when just trying to open her profile and I swiped on another person when trying to resize the window.

If there is going to be swipe functionality on the web, please require much more drag for it to work and allow a quick and easy undo. I also wouldn't mind swiping going away entirely, though.

**Comment by Nonononoki** [comment]
Swipe is now much harder to accidentally activate on desktop (bigger window width) with this commit: e9e818de4686193131b6fb93e30e58d500907898
