### ISSUE TITLE
Can't change "I want" setting

### ISSUE THREAD

**Issue by 12people** [Alovoa/alovoa#144]
Going into my profile, I can't seem to change the "I want" setting to anything else. No other option appears:
![image](https://user-images.githubusercontent.com/7361228/159218280-519b9ab5-9920-4458-8331-78d0ccf385da.png)

**Comment by Nonononoki** [comment]
You can only change it once every 24 hours to prevent abuse.
There is currently a bug that says exactly that after changing the I want value, will be fixed on the next update.

**Comment by 12people** [comment]
If that is the case, it'd be good to have a label under the input field saying "Can only be changed once very 24 hours to prevent abuse" in the web app, so that people understand why they can't change the value.

**Comment by Nonononoki** [comment]
Warn text has been restored with this commit: e9e818de4686193131b6fb93e30e58d500907898
