### ISSUE TITLE
Replace proprietary images

### ISSUE THREAD

**Issue by 12people** [Alovoa/alovoa#149]
The README states that "All images are proprietary, unless stated otherwise."

It'd be great to know which specific images are proprietary and to gradually replace them with open-source alternatives.

This is a necessity to allow self-hosting and decentralization via ActivityPub (as requested in #13).

**Comment by Nonononoki** [comment]
> It'd be great to know which specific images are proprietary#

As stated, all of them. This mostly affects the Alovoa logo and the logos of other companies.

**Comment by 12people** [comment]
@Nonononoki 

Why is this closed? Is self-hosting and ActivityPub out of the question, then? Or will all ActivityPub instances have to manually replace all graphics to be legally in the clear?

I understand why you might want a trademark on the logo, but it'd be good to allow redistribution in instances like those above. Perhaps with a proprietary license, but at least with carve-outs.

**Comment by Nonononoki** [comment]
Most logos of open-source projects are trademarked and protected, this project is not an exception. 
There are also Mastodon instances that removes the Mastodon logo (the most popular one being Trump's Truth Social), having a protected logo does NOT prevent and decentralization effort. 
As I said, there aren't that many images in the repo. Replacing them should only take a few minutes.

**Comment by 12people** [comment]
Trademark is something different from copyright.

Either way, a project has to give express permission to use copyrighted work, otherwise it CANNOT be used legally. (For an example, take a look at [Facebook's logo terms of use](https://www.facebook.com/brand/resources/facebookapp/logo).)

Being open-source doesn't mean other projects can legally use a logo — for example, Firefox famously denied Debian the right to use their logo for their Firefox distribution, so they changed the name to Iceweasel.

If the logo of this project will remain copyrighted and trademarked, it'd be good to publish terms under which it can be used.

**Comment by EchedeyLR** [comment]
Without a real fix on this, I fear that whoever want to selfhost it, will have to fork it and create its own distribution. Then, keep the changes maintained.

This breaks how the Fediverse works in almost any software built for it.
