### ISSUE TITLE
UserProfile controller doesn't fail gracefully for invalid input

### ISSUE THREAD

**Issue by fapdash** [Alovoa/alovoa#154]
### Behavior

Non Base64:
https://alovoa.com/profile/view/foo -> Illegal base64 character 7e

Valid Base64:
https://alovoa.com/profile/view/Zm9v -> Input length must be multiple of 16 when decrypting with padded cipher

### Analysis

The problem is that `UserDto` just throws the exception:
https://github.com/Alovoa/alovoa/blob/5d1035c8b44859207ae0dac07aa749b0c29a5fba/src/main/java/com/nonononoki/alovoa/model/UserDto.java#L235-L240

and the Controller doesn't handle them:
https://github.com/Alovoa/alovoa/blob/5d1035c8b44859207ae0dac07aa749b0c29a5fba/src/main/java/com/nonononoki/alovoa/html/UserProfileResource.java#L43-L46

### Suggestion

My suggestion would be something like this:

```java
public static Optional<Long> decodeId(String id, TextEncryptorConverter textEncryptor) throws NumberFormatException,
		InvalidKeyException, IllegalBlockSizeException, BadPaddingException, NoSuchAlgorithmException,
		NoSuchPaddingException, InvalidAlgorithmParameterException, NumberFormatException {
	try {
		String en = new String(Base64.getDecoder().decode(id));			
		return Optional.of(Long.parseLong(textEncryptor.decode(en)));
	} catch (Exception e) {
		LOGGER.debug(String.format("Couldn't decode id '%s'", id), e);
	}
	return Optional.empty();
}
```

And at the caller:

```java
Optional<Long> id = UserDto.decodeId(idEncoded, textEncryptor);
if (id.isEmpty()) {
	return new ResponseEntity<>(HttpStatus.NOT_FOUND);
}
```

I don't really understand why this method is on `UserDto` as it doesn't work with any of it's fields.
Looks like this method could be either on `TextEncryptorConverter` or on some other class that wraps `TextEncryptorConverter`, no?

**Comment by Nonononoki** [comment]
> I  don't really understand why this method is on UserDto as it doesn't work with any of it's fields.

Probably because the only instance where the id is decoded/encoded is to create and read the URL parameter of the user, even though it's a generic method.

Your suggestion looks good, feel free to create a PR! :+1:
