### ISSUE TITLE
Login requires different email

### ISSUE THREAD

**Issue by WeebNetsu** [Alovoa/alovoa#160]
I signed up with "example.social@gmail.com", but I had to login with "examplesocial@gmail.com" (remove the ".")... Why? This is of course allowed by google (thus the reason we still get the email, even without the '.' in the email), but I think this will confuse people, I recommend you add a message to tell users that they should remove any '.' in their email when logging in, because someone with little tech knowledge would probably think it's broken and won't come back to it or recommend it to other people

**Comment by WeebNetsu** [comment]
Well either that, or just remove the '.' from the email before comparing it to what is in the database

**Comment by Nonononoki** [comment]
Should be fixed with this commit: 8a15d6c5f16c7b6782553e8a67ca2cbd39e0299e
