### ISSUE TITLE
like does only work when like and dislike are displayed at the bottom.

### ISSUE THREAD

**Issue by Jirafey** [Alovoa/alovoa#166]
What can I do? I travel a lot so can't I change that to international?

**Comment by Jirafey** [comment]
I cannot like somebody: error occurred. Showing all arond the globe. The fdroid version.

**Comment by Jirafey** [comment]
Update: I see people from over 6k km now. Liking works 30% of the time

**Comment by Jirafey** [comment]
People reappear over and over

**Comment by Jirafey** [comment]
Like only works if it is displayed at the bottom. Liking by Swiping without likes and dislikes at the bottom produces no effects. People reappear

**Comment by Nonononoki** [comment]
This is intended. Users can only match each other if their preferences match each other. There was a bug that would show incompatible users too early, which has been fixed yesterday (0bea66f66d4cf9124bb6ac1163cb88a50927dddc). The platform will show "incompatible" users when no compatible users have been found (there is also a huge popup on the top when this happens.
