### ISSUE TITLE
Changing "I want" choice not possible

### ISSUE THREAD

**Issue by MagischerStock** [Alovoa/alovoa#167]
If I try to change my "I want" choice, there's only the option I already selected. It should be possible to change it at least once a day.

**Comment by Link2000** [comment]
This user too:

https://github.com/Alovoa/alovoa/issues/145#issuecomment-1082352042

**Comment by Nonononoki** [comment]
It's possible to change it once every 24 hours, but not possible within 24 hours after setting the initial value. I made it clearer in this commit when the user is in the onboarding page: 05991d7fe1a0288254b32e83f1079e070bae707b
