### ISSUE TITLE
Consider removing "you have never been found guilty for a sex crime or violence related crime" from the terms of conditions

### ISSUE THREAD

**Issue by Wallby** [Alovoa/alovoa#170]
I think the text in the terms of service that "By creating an account and using the service, you represent and warrant that: [...] you have never been found guilty for a sex crime or violence related crime." seems not smart. I.e. what if a person was convicted for a crime they did not commit? Also I think the whole "you have never been found guilty for [...] a violence related crime" doesn't make any sense whatsoever. E.g. with these terms a person that was a victim of racism in the past and perhaps lashed out and was then convicted for "a violence related crime" would not be allowed on the site, hence that would be victim shaming.

**Comment by Nonononoki** [comment]
Of course, these are edge cases that should be handled individually. The terms are there to protect the platform from lawsuits but can be enforced once enough proof have been found. In my opinion it's fine as is.
