### ISSUE TITLE
password reset non functioning

### ISSUE THREAD

**Issue by aha999** [Alovoa/alovoa#173]
Everytime i try to reset the password on the registered account, it says that An error occurred, please try again. 

I tried with the correct credentials first, but it didn't log me in, then reset, also doesn't work. Tried on PC and phone app. That's all the info i have, i'm afraid.

**Comment by Nonononoki** [comment]
There are two pages within the steps of resetting the password. The first one is the reset page (https://alovoa.com/password/reset) and the change page (https://alovoa.com/password/change/[id]), when does the error occur? 
And are you sure you entered the right email address? Please check the address (**yours**) that is sent to you by the system.

**Comment by aha999** [comment]
the email is correct. On the reset page i get "An error occurred, please try again", on the second link i get the same error. Yesterday i was logged in with this account.

**Comment by Nonononoki** [comment]
As you're currently the only one with this issue, please send an email to contact@alovoa.com with the associated email address

**Comment by aha999** [comment]
Turned out i was registered on a wrong website at https://alovoa.herokuapp.com/ . Just wondering, is there a reason for this website to be online and accessible to everyone ?

**Comment by Nonononoki** [comment]
Just a test site where I can test out some stuff that's not possible to test locally. Where did you even find that site? Both Google, DuckDuckGo and the github page show the correct link.

**Comment by aha999** [comment]
I found the website at the first link of your website that i saw. 
i typed "FOSS dating apps" into a search engine, and [this forum](https://lemmy.eus/post/2068) came up, the link was in this guy's comment, where Alovoa is in green text:
![image](https://user-images.githubusercontent.com/50620416/170299402-8e7c1950-fb43-452b-a525-a6f3f7d3b13f.png)

**Comment by aha999** [comment]
also here https://www.reddit.com/r/webdev/comments/m49xd1/i_made_a_100_opensource_dating_and_meeting_new/gqt8pfb
