### ISSUE TITLE
Change the LiberaPay link to the direct donation page

### ISSUE THREAD

**Issue by aha999** [Alovoa/alovoa#174]
Currently, the liberapay link goes to the Alovoa liberapay page, where you have to click the Donate again, so it's a 2 step process...

Please change the donation link in the github readme to https://liberapay.com/Alovoa/donate , so by pressing the Liberapage link, a person can donate more directly and a step is saved, being more convenient.

**Comment by Nonononoki** [comment]
The liberapay link is actually managed by github themselves (see https://github.com/Alovoa/alovoa/blob/master/.github/FUNDING.yml). 
One could argue that I can add can add a custom link, but I think there's a reason why github doesn't redirect you directly to the donate page.

**Comment by aha999** [comment]
If you check here, you will see that there is /donate link at the sidebar. https://github.com/fr3ts0n/AndrOBD 

<img src="https://user-images.githubusercontent.com/50620416/170283314-4727cd27-c76e-470b-b877-22f5bf4bda4c.png" width="200">


I think it would be a more direct method of donation, since users that see LiberaPay link and want do donate, there's no need to make more steps for them.
