### ISSUE TITLE
After failing to log in, the message display span is too short

### ISSUE THREAD

**Issue by aha999** [Alovoa/alovoa#175]
When failing to log in, an informational message is displayed, for which there is no time to read, because it's displayed for about a second.

Please extend the display time for this message.

Screenshot, the 1 second message in question is in the grey window:

![image](https://user-images.githubusercontent.com/50620416/170258763-68ae0ff4-bf38-414c-a671-d3547865cc80.png)

**Comment by Nonononoki** [comment]
Any suggestion on how long it should be? It's currently exactly 3´seconds long

**Comment by aha999** [comment]
As long as it's required to read the entire message with normal speed i guess.
After retrying i see that indeed it is indeed 3 seconds. Before it was 1 second at the time that i made the issue.
I've read it in normal speed and it took me about 9 seconds.

**Comment by Nonononoki** [comment]
Frontend moved to https://github.com/Alovoa/alovoa-expo
