### ISSUE TITLE
Alovoa should be renamed

### ISSUE THREAD

**Issue by aha999** [Alovoa/alovoa#178]
I think that Alovoa name is going to be very hard or slow to adopt amongst the public.

**Issues with the name:**
- Hard to remember
- Not "catchy"
- Sounds complicated
- It's tongue twisting
- Hard to spell
- Which part in the name is being emphasized ? This will cause a lot of confusion
- What does the name even mean?

**Examples** of naming in the most popular dating platforms:
- Tinder
- Bumble
- Grindr
- Match
- Hinge
- Clover

They are extremely simple, easy to remember, spell and everything else i mentioned.

This is a hands down amazing project and probably the best FOSS app, but i think that it should definitely be renamed to something simply better. I only found this project because i was specifically searching for it and someone mentioned it in a forum, where i couldn't even remember it, and can't even pronounce it confidently after saying it at least 10 times today.

**Idea:**

- Pin a new issue that you create yourself, called Renaming Alovoa, where you ask the community to give ideas on what name should be picked.
- Emojis could be used for upvoting/downvoting, then you would select the name by your feeling and community recommendation. 
- This plan could be mentioned somewhere on the website as a notification, which users get.

**Comment by Nonononoki** [comment]
I disagree with a few points and agree with others. Anyway, I don't plan to change the name any time soon.
```
Hard to remember
```
Very subjective. I think it's fine, but not perfect.
```
Sounds complicated
Not "catchy"
It's tongue twisting
```
True, but not everything needs to be catchy.
```
Hard to spell
```
Subjective. It's just 6 letters.

```
Which part in the name is being emphasized ? This will cause a lot of confusion
```
You can pronounce it however you want :)

```
What does the name even mean?
```
It's just a name. Tinder, Bumble, Hinge are also names that don't mean anything.
