### ISSUE TITLE
After pressing Save (settings), display a confirmation message

### ISSUE THREAD

**Issue by aha999** [Alovoa/alovoa#179]
In the settings, if you save your configuration, it would be reassuring and convenient, if a message was displayed below that, saying "Saved successfully". Currently the website just blinks.

![image](https://user-images.githubusercontent.com/50620416/170297547-12c59f80-a1d3-4889-afff-e6760032521a.png)

**Comment by Nonononoki** [comment]
Frontend moved to https://github.com/Alovoa/alovoa-expo
