### ISSUE TITLE
Add info text to Chats page when empty

### ISSUE THREAD

**Issue by aha999** [Alovoa/alovoa#181]
Currently if there are no messages, the Chats page is completely empty, like it didn't fully load, and it's distracting that there isn't any informational text.

Please add the info text to the Chats page if there are no messages, text at the center of the page, like "You have no messages at the moment".

<img src="https://user-images.githubusercontent.com/50620416/170304274-face6c47-8f70-4a8a-913f-75a6463f253e.png" width="700">

EDIT: same goes for Alerts page if it's empty.

**Comment by Nonononoki** [comment]
Frontend moved to https://github.com/Alovoa/alovoa-expo
