### ISSUE TITLE
Difficult to set up profile if geolocation fails

### ISSUE THREAD

**Issue by comradekingu** [Alovoa/alovoa#183]
Says it will be set once a search is made, but the earlier bottom nav is gone.
The profile can't be finished without location.

Would be nice to always have the bottom nav, and possibly be able to search in a link from the error message, or click it to request
the permission again.

**Comment by Nonononoki** [comment]
Not sure what the problem exactly is. You should be able to choose a location manually if geolocation fails. Could you take a screenshot?

**Comment by coderamm** [comment]
I have the same issue. I don't allow websites access to location by default. I received the same message as @comradekingu, that my location will be set once I make a search. In my case, I commited a (human) error in choosing my location and it would be nice to have the option of choosing it again. 
Maybe this could be a feature request:
1. Show chosen location in the profile page - this will help the user check if they indeed have the right location chosen
2. Give users the option of changing their location. Granted, this has other implications i.e., users will be able to choose any location and hence hide their actual location. But I think this is an acceptable compromise (and maybe even better from a privacy point of view)

**Comment by Nonononoki** [comment]
@coderamm You can freely change your chosen location on the search page by clicking on the cog icon on the top

**Comment by coderamm** [comment]
Now I see. So the steps to change location on the search page are: Settings button (cog) -> Search. Thank you.
I suggest renaming the "Search" button in the settings pane to something more representative. Like "Choose location". The first time I saw that button I just assumed it would redo the search with the changed distance.

**Comment by Nonononoki** [comment]
Good idea, but I would choose another name because it does more than just choosing location. Name would probably be hidden on phones anyway because of space constraints, so not a priority right now.

**Comment by coderamm** [comment]
Not sure about the phones - I'm using it on a desktop browser. 
You are right, it not only lets you choose the location but also submits does searches users with the newly selected criteria. So maybe "Set location and search"? But no strong preference for what the button says, what is important is that the function of the button must be immediately clear to the user. I think we agree on that point.

**Comment by Nonononoki** [comment]
Frontend has moved to https://github.com/Alovoa/alovoa-expo
