### ISSUE TITLE
Alovoa development/support chat platform

### ISSUE THREAD

**Issue by aha999** [Alovoa/alovoa#187]
Alovova currently doesn't have a community focused chatting group available for any development question and support.

I think that the best platform for this would be Matrix, since it's free, open source and decentralized. Try the [Element](https://element.io/) software for it, it's pretty good and popular.

I took liberty to create a [Alovoa Chat on Matrix](https://matrix.to/#/#AlovoaDating:matrix.org), if you join (main dev @Nonononoki ?) i will make you an admin and i will demote myself to a regular user. if you don't like this i can delete the community. Or i can help you with moderating.

**Comment by Nonononoki** [comment]
Unfortunately I'm not very active on Matrix, but I joined. If you want to you can keep the admin status and help with moderating :)

**Comment by aha999** [comment]
Can you join the 3 alovoa rooms so i add you as admin ?

**Comment by aha999** [comment]
@Nonononoki Can you please join This Matrix channel so i add you as admin ? :)

**Comment by Nonononoki** [comment]
@aha999 Done :)
