### ISSUE TITLE
Improved sharing thumbnail

### ISSUE THREAD

**Issue by aha999** [Alovoa/alovoa#194]
Alovoa currently has a big parrot icon, that is weirdly cropped, when sharing Alovoa to people, which then looks unattractive.

I suggest, you implement a more modern and attractive social media sharing thumbnail.

Current thumbnail:

![image](https://user-images.githubusercontent.com/50620416/177048475-eb625502-cf97-4902-8a3a-a00a3bdbacee.png)

**Comment by Nonononoki** [comment]
Added a new sharing image with this commit: 89adc6bd2167eeabad938c3c14bcede99b81bc24
Could you tell me if it works?

**Comment by aha999** [comment]
It works, looks great! 
![image](https://user-images.githubusercontent.com/50620416/182052094-7f4e38b4-5f47-47b8-ba72-62abf0e548c8.png)

**Comment by aha999** [comment]
Also, if i share it via other networks like Facebook, the resolution seems to be low and jpeg fragments can be seen, can the resolution be improved ?

![image](https://user-images.githubusercontent.com/50620416/182052257-4dfc8f69-4be9-4bff-83ea-1a1bcdbc1489.png)

**Comment by Nonononoki** [comment]
> Also, if i share it via other networks like Facebook, the resolution seems to be low and jpeg fragments can be seen, can the resolution be improved or is this the social platform issue ?
> 
> ![image](https://user-images.githubusercontent.com/50620416/182052257-4dfc8f69-4be9-4bff-83ea-1a1bcdbc1489.png)

Could be both. The share image's width is 800px right now, which is adequate, but not really high res. Will probably increase it to 1200px in the next update.
