### ISSUE TITLE
Loading doesn't stop

### ISSUE THREAD

**Issue by aha999** [Alovoa/alovoa#196]
When i press the Search function in the gear menu, it starts loading and doesn't fully load, but it keeps loading. After clicking a restart tab in the web browser, the Alovoa reloads normally.

This seems to be a bug.

![image](https://user-images.githubusercontent.com/50620416/177060062-42e958c5-8581-42d8-92ac-79890506c387.png)

**Comment by GeraldSoellinger** [comment]
same for me

**Comment by Nonononoki** [comment]
Should be fixed with this commit: be12ecdbffc95454421689eab3235fa3b7b7e96f

**Comment by GeraldSoellinger** [comment]
yes, works now. 
Thank you! :)
