### ISSUE TITLE
Profile Page does not update

### ISSUE THREAD

**Issue by GeraldSoellinger** [Alovoa/alovoa#197]
Hello!

I can not add more profile pictures nor can I change the profile description.
But other than that I like the application a lot.

BR
Gerald

**Comment by Nonononoki** [comment]
More info needed. Could you take a screenshot? What exactly is not working?

**Comment by GeraldSoellinger** [comment]
I have tried to add more pictures on my laptop running ubuntu 20.4 with firefox and with my phone running Android 11 and Chrome browser.

The button seem to notice that I try to press it, but there does not open a window to select an image.

**Comment by Nonononoki** [comment]
Now fixed with 7a91064c2be64ae3f5ead2fcdae0e5968b83841e
Problem was autocomplete not working while having the maximum number of interests

**Comment by GeraldSoellinger** [comment]
yeah, working :)!!!
