### ISSUE TITLE
Impossible delete account

### ISSUE THREAD

**Issue by cadu1996** [Alovoa/alovoa#200]
The delete Account link doesn't work.

Maybe there is a problem with the captcha or submit button doesn't work

**Comment by Nonononoki** [comment]
It seems that it just takes a while. Can you try again but wait about 15 seconds after clicking the submit button?

**Comment by cadu1996** [comment]
I tried many times and always returned: "An error occurred. Please try again".

 I waited too but I got the same error message.

**Comment by cadu1996** [comment]
I tried many times and always returned: "An error occurred. Please try again".

 I waited too but I got the same error message.

**Comment by Nonononoki** [comment]
Only other reason I can think of right now is that you're logged in with a different account that did not request the deletion

**Comment by coderamm** [comment]
I can confirm that account deletion works as it should. There is however, a time delay as noted above.

**Comment by Nonononoki** [comment]
Found this issue. The translation for Dutch was messed up, fixed in this commit: 65fb4e181ea272a07921a92e59ac5ef02f77d856

**Comment by NeoMixlax** [comment]
My problem was that I pressed the deletion button in my profile settings many times... Then, there were many links sent to my email. The only link that worked was the last one. Be careful with that.
