### ISSUE TITLE
Forgot password button doesn't work

### ISSUE THREAD

**Issue by theshininginception** [Alovoa/alovoa#202]
https://alovoa.com/password/reset returns a blank page with "user_not_found" error message.

**Comment by Nonononoki** [comment]
Works for me, did you make sure that the email address is correct? It must 100% match (minus case) the one sent by the system.

**Comment by Nonononoki** [comment]
Thanks for the report! Issue has now been fixed with 51c34ef8fb88615d45aadfa86bf7bf4c3149b7a2

**Comment by Nonononoki** [comment]
@theshininginception Could you try again?
