### ISSUE TITLE
Questions to help with translation

### ISSUE THREAD

**Issue by gallegonovato** [Alovoa/alovoa#207]
Good afternoon:

I am looking at weblate to help translate the application.

And I have some doubts about some entries. I don't know if you could give me an example or the context.

The entries are:

SI . I don't know if you mean yes, International System of Units, the function si , etc...

mi: Xiaomi, etc..

A hug and thanks for your help and time.

**Comment by Nonononoki** [comment]
All the names are in English, **si** in this case means **International System of Units**. **mi** is short for **miles**, a unit of distance mostly used in the US, km is used for kilometers.

**Comment by gallegonovato** [comment]
Good afternoon:

First of all thank you very much for your help.

The bad thing is that in some languages they are or can be translated in very similar ways. For example:

Si in Spanish is also si. Or Sistema Internacional de Unidades (As I put it above). 

A hug and thank you for your help and sorry for the inconvenience caused.
