### ISSUE TITLE
Allow to use a custom browser. Do not open Google Chrome on the start.

### ISSUE THREAD

**Issue by AIGeneratedUsername** [Alovoa/alovoa#215]
## Problem

"alovoa" opens Google Chrome. I do not use Google products due to privacy reasons. I have another browser installed as a default.

## Step to reproduce

1. Install any privacy-friendly browser (e.g. Privacy Browser or FOSS Browser). Set the browser as a default.
2. Open "alovoa" app.
4. The "alovoa" app opens Google Chrome.

## Expected behavior

To be able to use a custom browser. Do not open Google Chrome by default.

**Comment by Nonononoki** [comment]
It actually opens in any browser that is set to default. It actually opens in Chrome when installed from the Playstore. Could you try installing the app in F-droid?
Also, it's better to open the issue in the proper [repo](https://github.com/Alovoa/alovoa-android)

**Comment by AIGeneratedUsername** [comment]
Moved to https://github.com/Alovoa/alovoa-android/issues/15
