### ISSUE TITLE
Create account via E-mail not working

### ISSUE THREAD

**Issue by ThiloteE** [Alovoa/alovoa#216]
As the title says. I wanted to have a look at Alovoa and tried to create an account. I encounter an error during account creation, which says "something went wrong". I have not received any e-mails from Alovoa that allows me to confirm the account creation. The paradox thing is that the e-mail is now "taken" and I cannot try to register a new Alovoa account with this e-mail address.

I cannot reset my password via "forgot password", because it triggers another error, but it also says an e-mail has been sent. Still, I have not received these e-mails.

To cross check, I used two different e-mail addresses from two different e-mail providers (web.de / disroot.org) and it happens for both. I also checked my spam-folders.

I don't want to register with a facebook or google account.

**Comment by Iizuki** [comment]
Email registration worked just fine for me yesterday.

**Comment by ThiloteE** [comment]
Maybe it is a browser thing? I use Mozilla Firefox

**Comment by Iizuki** [comment]
Me too. I used `mailer.me` email domain.

**Comment by Nonononoki** [comment]
Seems to be a unique error, please send an email to contact@alovoa.com
