### ISSUE TITLE
Turkish Localization Added.

### ISSUE THREAD

**Issue by ramazansancar** [Alovoa/alovoa#224]
Hello,
I provided some support in Turkish localization. Maybe this place is not very controlled. Can you check and add?

https://hosted.weblate.org/projects/alovoa/alovoa/tr/

**Comment by Nonononoki** [comment]
Unfortunately there were some merge conflicts on Weblate which I just resolved.

The Turkish translation has been merged to the master branch and is now available on the Testing Website (https://beta.alovoa.com/?lang=tr).

Will be available on the Main Website in a few days after testing.
