### ISSUE TITLE
Possible failures in Weblate

### ISSUE THREAD

**Issue by gallegonovato** [Alovoa/alovoa#253]
good afternoon @Nonononoki 

I have a doubt with this chain. https://hosted.weblate.org/translate/alovoa/alovoa/es/?q=state:%3Ctranslated#comments

For example, in Spanish you start writing from the left and end up on the right.

And it says #only for languages from right to left.

And it always warns me that it is untranslated. I don't know if there is a way to avoid that it comes out as untranslated?

And also if I look at other languages that begin to write like Spanish: English, French, etc ... appears translated.

So, I translate ltr as: https://es.m.wikipedia.org/wiki/Long_terminal_repeat

a hug

**Comment by Nonononoki** [comment]
I don't know much about weblate myself, you can just ignore the warning.
It's an unused word that does not need to be translated anymore.
