### ISSUE TITLE
Czech language

### ISSUE THREAD

**Issue by zen0bit** [Alovoa/alovoa#258]
### Czech language finally done...
<a href="https://hosted.weblate.org/engage/alovoa/cs/">
<img src="https://hosted.weblate.org/widgets/alovoa/cs/alovoa/multi-auto.svg" alt="Stav překladu" />
</a>

**Comment by Nonononoki** [comment]
Thank you for your contribution. There are some conflicts on weblate, but I'm sure it'll be merged to master soon :)

**Comment by zen0bit** [comment]
I aproved one missing string otherwise LGTM
