### ISSUE TITLE
E-mail - Matrix

### ISSUE THREAD

**Issue by aha999** [Alovoa/alovoa#259]
I can't seem to find an e-mail for support for alovoa.

I would like to say to the main developer, that it would be great if he came by the [Alovoa Matrix channel](https://matrix.to/#/#general_alovoa:matrix.org) sometimes as users have questions and comments! 

Have a good day :)

**Comment by sradigan** [comment]
This is under the "imprint" page. I thought that was a little strange, maybe a language thing?

https://alovoa.com/imprint

**Comment by maltfield** [comment]
:de:

**Comment by Nonononoki** [comment]
Imprint has been changed to Contact
