### ISSUE TITLE
invalid characters in messages in spanish

### ISSUE THREAD

**Issue by mvalberto** [Alovoa/alovoa#263]
characters like ñ , or tildes are displayed incorrectly in messages
![image](https://user-images.githubusercontent.com/81685321/222416840-69a512cb-45c9-4e4c-a055-253e67738f51.png)

**Comment by Nonononoki** [comment]
Work for me. Could you give me more info? Device, OS, browser, etc.

**Comment by mvalberto** [comment]
chrome for windows, and android all devices in sapanish
running in windows server 2019 in spanish
try to force the utf-8 switch to html..
![image](https://user-images.githubusercontent.com/81685321/222445578-d4118d6c-688f-4903-acc4-c41c833fa0bb.png)

and when loaded in the browser it doesn't recognize the utf8 
![image](https://user-images.githubusercontent.com/81685321/222445863-28750704-ee98-47a8-a81f-e7c21c84e97b.png)

**Comment by mvalberto** [comment]
It is very strange, the problem only occurs in messages, in the profile the representation of characters is correct.

I keep investigating

**Comment by Nonononoki** [comment]
Frontend moved to https://github.com/Alovoa/alovoa-expo
