### ISSUE TITLE
Location not updated

### ISSUE THREAD

**Issue by sedrubal** [Alovoa/alovoa#275]
Thanks for the great app!

I'm not sure if I'm supposed to set my location manually or if it is set automatically. However, I moved from one country to another, but the location is not updated and I can't find an option in my profile settings to change it manually. What am I doing wrong?

**Comment by Nonononoki** [comment]
Hi,

location is updates automatically when you search for new users in the Search page. Let me know if you have further questions.

**Comment by sedrubal** [comment]
Thanks! Then, something seems to be broken. The country flag next to my name in my profile remains the same and it seems like the app tries to show me users near to my old country.

**Comment by Nonononoki** [comment]
The old location will be used if no location has been found. Could you press on the gear icon in the Search page and then search for users?

**Comment by sedrubal** [comment]
Thank you. By doing so the app asked for permission to access my location (I had to reinstall the app. That's why the app hasn't have the permission anymore). Now my location was updated.
But I think it is not intuitive that I have to press the search button myself. Why isn't the location updated every time when I open the app, for example?

**Comment by Nonononoki** [comment]
What app are you using?

**Comment by sedrubal** [comment]
Alovoa Lite on Android (f-droid version) and the election desktop client from Flathub.

**Comment by Nonononoki** [comment]
Frontend has moved to https://github.com/Alovoa/alovoa-expo
