### ISSUE TITLE
Email regristration, and thus the entire app, cannot be used.

### ISSUE THREAD

**Issue by Lind0rm** [Alovoa/alovoa#276]
As titled, regristration permanently fails no matter how many times you click the link; cant even regeister the email again since it falsly claims it was already registered.
Hence, the entire app is useless.

**Comment by Nonononoki** [comment]
Hi, 
sorry that you're facing issues. If possible, could you try to rest your password?
https://alovoa.com/password/reset

**Comment by Nonononoki** [comment]
Closing due inactivity
