### ISSUE TITLE
Getting HTTP Error 409 when trying to open alerts or chats

### ISSUE THREAD

**Issue by Foxdynamics** [Alovoa/alovoa#279]
Hello there,

since yesterday evening I get an Error 409 in the Browserconsole, when I try to open the alerts page or my chats.

![Bildschirmfoto_2023-06-27_10-06-58](https://github.com/Alovoa/alovoa/assets/134605669/868f1877-3391-45a5-a8d0-e1d85015f02e)

I know this error when there are profiles that don't match me, but not being able to open the alerts page is new.

Are there some servserside issues or is there a problem with my profile?

**Comment by Nonononoki** [comment]
Sounds like a server side issue. Could you reproduce it and give me the exact time the issue happens?

**Comment by Foxdynamics** [comment]
Thanks for the fast reply. I just tried again at 11:30 a.m. (UTC+2) to access the /alerts page.
If I can somehow provide more specific information, feel free to let me know.

**Comment by Nonononoki** [comment]
Have you been using the F-droid build of Alovoa lately? It's currently broken, the location is stored in a wrong format. Please update your location in the browser.

**Comment by Foxdynamics** [comment]
Ah, indeed I use the F-Droid version. Strange thing is that it still worked with this version until about 11pm last night.

I have nevertheless uninstalled the app once and updated the GPS signal again directly via the Fennec browser. Unfortunately, still the same result.

I still remember swiping a last remaining person in my search window several times to the left and then to the right.

When I call the search page itself, I also only get a completely blank page in Fennec except for the background image. I don't think that was the case the day before yesterday:

![Bildschirmfoto_2023-06-27_21-04-27](https://github.com/Alovoa/alovoa/assets/134605669/65f739af-e1ce-4f1f-904f-11a76911eefb)

Could it be that I got blocked from the server by swiping left too many times in too short intervals or maybe unintentionally messed up something in the database?

The profile can still be accessed normally. However, when I want to view the non liked users at the bottom, I get this funny error screen:

![Bildschirmfoto_2023-06-27_21-15-47](https://github.com/Alovoa/alovoa/assets/134605669/47fa7635-eb9f-4e9c-abff-7ba5f14c2fe1)

Here, however, I don't know exactly whether it has only been coming since last night or whether it would have come the day before yesterday.

When I want to view the liked users, similar to the alerts page, nothing comes up.

**Comment by Nonononoki** [comment]
Can you go to the search page, click on the cog and start a search?

**Comment by Foxdynamics** [comment]
Yes, the circle animation appears very briefly. Then the background image without everything else is there again and the error persists.

**Comment by Foxdynamics** [comment]
Quick update: Have now deleted and recreated the account. Now it works again. :)

**Comment by Nonononoki** [comment]
@Foxdynamics Sorry for the inconvenience, the next F-droid version (v.1.4.0) will have a fix for the location
