### ISSUE TITLE
crypto-system architecture and threat model

### ISSUE THREAD

**Issue by ansuz** [Alovoa/alovoa#28]
Hi,
I've thought about crypto-systems that could be used for dating apps before, and it's nice to see someone giving it a try.

The readme says that sensitive user info is encrypted but it doesn't mention how.

1. Is there one global encryption key for the database or does each user have a key?
2. Does the server encrypt for users, or is data encrypted on the client to ensure that the server doesn't have access?
3. If users have distinct keys: how are they generated? Are they specific to a device or can an account be accessed from multiple devices?

I can probably infer the threat model from there, but it would be nice to have it clearly laid out.

1. Exactly what information is intended to be protected?
2. Who should have access to sensitive data? Who should not?
3. What attacks do you consider out of scope?

Thanks!

**Comment by Nonononoki** [comment]
There are no plans for a crypto-system architechture for now.

1. There is a single encryption key on the server, for all encrypted data
2. Server decrypts user data on-the-fly, no data in decrypted by the user

1. Sensitive user information like email address, location data and messages for now. I can encrypt more but I think those are the most sensitive data that resides in the database (for now).
2. Email: Only user. Geolocation: Only user. Messages: Both user and recipient. Server obviously has access to all of those if needed. 
3. English is not my native language, can you clarify?
The server automatically decrypts the encrypted data, but it does not send them to anyone. If the server were to compromised the attacker would get nothing. Same with the database, as the information they would get are too non-identifying to be of any use.
Possible attacks:
Attacker somehow redirects the user to their site with my url.
Attacker replaces the server with their own server.
Attacker has access to the RAM and reads the unencrypted information there.
Attacker has access to the database AND private key.

**Comment by ansuz** [comment]
Thanks for taking time to answer!

I was mostly interested in whether the use of encryption was related to the stated goals of _No selling your data_, _No unsecure servers_. For example, whether the server operators would be incapable of selling your data because they didn't have access to it due to end-to-end-encryption.

Since the server performs the encryption, I think the notion of _not selling your data_ is less a feature of the software and more a decision made by the the server's operator. From a user's point of view it would not be possible to check who had access to their data.

By _threat model_ I mean to ask:

* When you say _unsecure servers_, precisely what security issues are you addressing?
* What kind of attacks are prevented by your use of encryption that would otherwise be possible?

In other words, since the (symmetric) encryption key must be stored on the server as well (at least in memory), under what circumstances would an attacker gain access to the database but not the key?

I can think of:

1. if the host server's database or firewall are incorrectly configured such that the database is exposed directly to the internet without the access control that is implemented by the application server
2. if the attacker gained access to the server as an unprivileged user and could not read the key (because of read permissions)

> If the server were to be compromised the attacker would get nothing.

This seems misleading because it depends heavily on exactly how the server is compromised. I agree that the application is more resilient against misconfiguration than it would be without encryption, but it doesn't go as far as I was hoping.

In any case, thanks again for answering!

**Comment by Nonononoki** [comment]
Not selling your data is indeed just my decision. 

While end-to-end encryption is great, it does not work very well with this kind of application.
Emails can't be sent from the server, you have to store it in plain text.
You can't search for people near you, because your location data is e2e encrypted.
You can only use the application on one device or have to carry your key on all devices (the goal of this application is to become widespread, and convenience is also a major point).

And you're right, if an attacker has root access to the web server he will be able to get all the keys and user info (except plain text password). If you have any more questions then please ask :)

**Comment by Glitchy-Tozier** [comment]
Implementing E2EE shouldn't be impossibly difficult though, right? 

Signal's code and the Signal protocol are open source, so using them should do the trick, right?

**Comment by Nonononoki** [comment]
@Glitchy-Tozier There is a reason why Signal has no web app, because transferring your private key securely over multiple platforms and browsers is unintuitive and a pain, not to mention very difficult.

**Comment by Glitchy-Tozier** [comment]
That makes sense, I was going into it with dating apps in mind. Of course, Signal _does_ have a desktop client, but the process of adding your chats there isn't super comfortable.

Using the users passwort to generate a private key still should work though.  :)
