### ISSUE TITLE
How to send a Message?

### ISSUE THREAD

**Issue by setuidroot** [Alovoa/alovoa#281]
I signed up for this site out of interest and respect for the open source nature of the code... I cannot find out how to send someone a message.  Does anyone know how to do this?  This feature shouldn't be hidden.

I hope to one day contribute PRs to this project as I continue to learn programming.

Thanks.

**Comment by Nonononoki** [comment]
You can send a message after a match. Should have been in the onboarding process, last page I believe. There are plans to make this even more visible.

**Comment by setuidroot** [comment]
Oh, I see.  For future reference, a "match" means both users have to like each other for you to be able to send messages to each other.  I think this is limiting to a website that's already "struggling" (relative term, not meant to be derogatory) with acquiring users.  Dating sites are a pretty competitive industry, as it's all about the name brand of the site.  I want this site to be successful because I'm sick of dating sites completely selling out and making you pay just to message a user.  Plenty of Fish used to be good, but now I can't even sign-up because it just errors out on registration.  OkCupid used to be good, but now you have to pay a monthly fee to be able to message users.  There are no good free dating sites anymore and it sucks... I think Alovoa has an open market for free dating sites, but capturing new users is the issue (that's hard to solve without money for advertising).  Hopefully Alovoa is like the future Bitcoin, I always loved Bitcoin (way back in ~2011) and it took off lol.

I'm not judging the site in a negative way here, I think it's a wonderfully made UI that gives it a lot of potential and I want to see it succeed.

Anyways, you can close this issue as solved if you'd like.  Otherwise, I'll probably close it after awhile.

Thanks for your quick reply.
