### ISSUE TITLE
[FEATURE] Replace SQL Database by NoSQL Solution (e.g. Redis)

### ISSUE THREAD

**Issue by ip6li** [Alovoa/alovoa#307]
**Is your feature request related to a problem? Please describe.**
In large environments MariaDB/MySQL have a poor performance. Same is true for Postgresql. While simulating DoS attacks against my Alovoa test installation, SQL queries were a bottleneck, even on quite powerful server hardware and optimized MariaDB configuration.

**Describe the solution you'd like**
It seems that Alovoa does not need transaction safety, so a Redis cluster seems to be sufficient to store user data. For security reasons user and secret management should be handled externally, e.g. by an OIDC identity provider. In comparison to looking for profiles, pictures and videos login, password change happens quite rarely. Such a solution would be able to handle a million of users even on quite modest hardware requirements with exception of storage requirements.

**Describe alternatives you've considered**
Oracle RDMS is a SQL solution with is also able to handle large number of parallel requests, but their licences are really very expensive. An other way is to fiddle with Postgresql table partitioning. Last resort is to use AWS Aurora, but using such cloud services is also very expensive.

**Additional context**
Fortunately Spring Boot support Redis and other distributed noSQL solutions out of the box. So it should be really considered to throw away that old SQL stuff, if transaction safety is not really a requirement.

**Comment by Nonononoki** [comment]
I never heard of Redis before, but it seems that Redis is used mostly used in combination with an existing database like MariaDB.
Switching an existing database with gigabytes worth of data is hard, and using Redis to cache Redis would be optimal.

**Comment by ip6li** [comment]
Redis supports in-memory storage and persistent storage. In-memory storage is good choice for caching, but may still suffer on not cachable SQL data. Persistent storage in cluster mode is not transaction safe.

Maybe using persistent Redis is a good choice for large blobs:

* Collect images and videos from SQL and safe them with an unique key in Redis cluster.
* Instead a blob SQL db needs to store that key only.

**Comment by Nonononoki** [comment]
Closing this issue because replacing the existing database with ten of thousands of users is not feasable. A separate issue may be created to use Redis as a caching solution.
