### ISSUE TITLE
[BUG] Unable to sign in without "Remember me"

### ISSUE THREAD

**Issue by Nonononoki** [Alovoa/alovoa#315]
Only affects e-mail sign in. You have to explicitly disable it when logging in to reproduce the issue.

**Comment by Valeri12580** [comment]
I can handle the task if you assign it to me

**Comment by Nonononoki** [comment]
> I can handle the task if you assign it to me

I already have a fix ready. Should be done by tomorrow or so.

**Comment by Nonononoki** [comment]
Fixed 74b8dce238045913f4deeabcc825f91e10995efa
