### ISSUE TITLE
[BUG] Can not like user back

### ISSUE THREAD

**Issue by Endededed** [Alovoa/alovoa#333]
There is a user that likes me, but I can not like them back, even though they show up in my search.

The only reason I can see for that is that they have set their preferred age range to 38 - 99 and I am below 38.

1. I expect to be able to like anybody who shows up in my search.
2. I expect to be able to like anybody who likes me, regardless of matching criteria

![1](https://github.com/Alovoa/alovoa/assets/152708026/d1e66ddb-1b76-446a-9e6c-6faffca7a7b6)
![2](https://github.com/Alovoa/alovoa/assets/152708026/c476eb62-f43d-4dc1-a077-8b74da73adac)
![3](https://github.com/Alovoa/alovoa/assets/152708026/4cab0ac6-a655-45d0-a2bc-eb18a743c8ce)

**Comment by Nonononoki** [comment]
Yes, your preferred ages have to match. But I think you make a great point. 
Usually you can only see compatible users, which means this problem doesn't happen unless the use changes their preferences afterwards.

**Comment by Endededed** [comment]
Also I think if they went out of their way to like me, the preference setting should not matter.

**Comment by Nonononoki** [comment]
Should be fixed now dbe7851486a1e05737a100220189d97c1ccc06cc
