### ISSUE TITLE
Donation tracking via OpenCollective [BUG]

### ISSUE THREAD

**Issue by jeffrey734** [Alovoa/alovoa#336]
Hi, so I know it's not such a big trhing, but it seems like the donation tracking via OpenCollective doesn't work. I think it's a nice idea to see who support the app, so as there's many places to support it, they should work.
I gived one by Ko-fi to and it worked, but I looked at every platform that is proposed and OpenCollective seems to me the best option as it seems very transparent. It propose to show a public budget and and the whole income.
It would be interresting to already have an overview of what does it cost to maintain the app.
Sure it's a non profit project, but it's not to make maintainers pay alone for it.

**Comment by Nonononoki** [comment]
Unfortunately, I don't think OpenCollective supports any kind of mechanism to track donations.

**Comment by jeffrey734** [comment]
Ok, maybe it's a little bit more complicated, maybe a script could read the donors page and update it in the app, or read it from email confirmation.
It could worth a try to ask them if they can add this feature too.

I don't really know what you need. I'm still looking at the repo to have an idea how it works, but it's more complicated for me as I'm not a developer but a system administrator and still a junior one. I'll keep looking where I could help and keep looking to share my reviews and thoughts.

**Comment by Nonononoki** [comment]
I need some kind of webhook, the donation data needs to be sent to a specific URL after each donation.

Examples: 
https://help.ko-fi.com/hc/en-us/articles/360004162298-Does-Ko-fi-Have-an-API-or-Webhook-#i-want-to-use-the-ko-fi-api-for-my-page-0-1
https://www.buymeacoffee.com/app/webhooks/docs

**Comment by jeffrey734** [comment]
Good thanks. I'll share that with them.
Also to avoid confusion, I'm not sure if there's a purpose for that, but there are two other pages using alovoa name. It's probably better to remove them as you seem to be the owner of those too.

https://opencollective.com/alovoa_love
https://opencollective.com/alovoa_huntr

**Comment by jeffrey734** [comment]
Hi, I got some news from them and it seems like they support it. The documentation is here. Does it seems like what you need? Does it look complicated?
https://docs.opencollective.com/help/collectives/collective-settings/integrations#webhooks-generic-slack-discord

**Comment by Nonononoki** [comment]
Sadly, the Open Collective Foundation is shutting down. (https://blog.opencollective.com/open-collective-official-statement-ocf-dissolution/) Closing issue.

**Comment by wiki-me** [comment]
open collective is till available , see [this](https://opencollective.com/opensource/updates/regarding-the-announcement-to-dissolve-open-collective-foundation):

> For collectives currently hosted by Open Collective Foundation, you may be curious to know more about Open Source Collective and our fiscal hosting offering. Open Source Collective is a 501(c)(6) nonprofit fiscal host that only hosts open source software-related projects. If your collective works in the open source community, you may be eligible to be hosted by us. However, it is essential to be aware that as a 501(c)(6) organization, there may be restrictions on funding opportunities from specific donors who are limited to funding 501(c)(3) entities. Additionally, there may be constraints on transferring funds from a 501(c)(3) fiscal host to a 501(c)(6) fiscal host.

in fact the alternative fiscal host is [thriving](https://projects.propublica.org/nonprofits/organizations/822037583).
