### ISSUE TITLE
[FEATURE] Add account deletion form in /imprint 

### ISSUE THREAD

**Issue by Nonononoki** [Alovoa/alovoa#337]
Allows the user to request account deletion without being logged in.

**Comment by jeffrey734** [comment]
What would be the purpose of that? In case of loosing access of the account? How to confirm that the person asking for the deletion own the account?

**Comment by Nonononoki** [comment]
> What would be the purpose of that? In case of losing access to the account? How to confirm that the person asking for the deletion owns the account?

The purpose is that I have received multiple deletion request via the contact form and email. And verification email will be sent to confirm the owner of the account, as it is currently implemented.

**Comment by Nonononoki** [comment]
Done ff152eca816cd78aefd88b7e92353aa739e40b02
