### ISSUE TITLE
[FEATURE] Email notification on likes, matches and messages

### ISSUE THREAD

**Issue by Nonononoki** [Alovoa/alovoa#342]
- Add UserSettings class to User.java (with booleans emailLike, emailChat and emailMatch). The method userToUserDto should only expose settings if it's the current user.
- Add POST endpoints (/user/settings/emailMatch with a boolean body)
- Add new email templates for each email type
- Add at least the English translation, other languages can be added later.

Nice to have:
- Remove Webpush related code, as it's not needed anymore
- Create a ticket in alovoa-expo so you can change the settings in the frontend as well

**Comment by Nonononoki** [comment]
@pranavbalakrishnan4100 Sure and thanks :)

**Comment by pranavbalakrishnan4100** [comment]
[ERROR] Failed to execute goal com.github.buckelieg:minify-maven-plugin:2.0.1:minify (default-minify) on project alovoa: Execution default-minify of goal com.github.buckelieg:minify-maven-plugin:2.0.1:minify failed: A required class was missing while executing com.github.buckelieg:minify-maven-plugin:2.0.1:minify: org/codehaus/plexus/util/DirectoryScanner


I'm facing this error when i try to build the project? Any idea how it can be resolved? @Nonononoki

**Comment by Nonononoki** [comment]
Have you tried 
**_mvn clean install_**
At root?

**Comment by pranavbalakrishnan4100** [comment]
Yep, this happens when I execute mvn clean install.

**Comment by Nonononoki** [comment]
Not sure where the problem is, as I get no errors locally, on the server and on github actions. My guess is to update maven to latest version and update to latest JDK 17. Also remove your location .m2 folder.

**Comment by pranavbalakrishnan4100** [comment]
Removing the .m2 folder and building it again solved it, thanks.

**Comment by pranavbalakrishnan4100** [comment]
Hi @Nonononoki , apologies if i'm asking too many questions. But I'm a newb and just figuring things out. 

Any reason why the project wont run without Facebook and google oauth client keys in application.properties. Curious because nothing about this was mentioned in the document. Nothing is mentioned about the admin mail id and database encryption keys either. Would appreciate it if you can shed some light on this.

**Comment by Nonononoki** [comment]
Not sure why is doesn't work without, but you can simply use the missing values from the test profile: https://github.com/Alovoa/alovoa/blob/master/src/test/resources/application-test.properties

**Comment by pranavbalakrishnan4100** [comment]
I'm trying to debug and understand the code base, when i run it on localhost and click on the register or log in buttons it simply redirects to index.html. What am I missing out?

**Comment by Nonononoki** [comment]
The code is split in two. One for back end and basic HTML pages and one for the app frontend. You need alovoa-expo to run the frontend https://github.com/Alovoa/alovoa-expo. But this ticket only covers the back end part. As long as the unit tests run you're good to go!

**Comment by Nonononoki** [comment]
a89c58093b946f5928fca226bb82467b04573839
1c1d58137791c612b4010ebef5c909f828f513c2
7add660c05191d7fa94aab582d195ffe2b0f5fe0
