### ISSUE TITLE
[FEATURE] Add message to likes

### ISSUE THREAD

**Issue by Nonononoki** [Alovoa/alovoa#343]
Users can leave short messages when liking other users. 
Name: Compliment
Max 120 characters.

**Comment by jeffrey734** [comment]
Good this is very important so we can share a part of our personality and adapt it to the person we want to talk. Making this function paid on other app is ridiculus. Actualy some offer it and I usualy tend to prefer those app.

**Comment by Nonononoki** [comment]
Done 44937593246138040ca36cbc7af3ce2b7105673b
