### ISSUE TITLE
[BUG] Can't like incompatible user

### ISSUE THREAD

**Issue by wileyfoxyx** [Alovoa/alovoa#346]
**Describe the bug**
List of possible but incompatible matches doesn't have like/dislike buttons. When trying to like a user, an error appears: "An error occured. Please try again."

**To Reproduce**
1. Run out of possible compatible likes
2. Swipe right on any person to try and like them
3. See error

**Expected behavior**
Like is being sent without errors; like/dislike buttons available on profiles

**Desktop:**
 - OS: Windows 11
 - Browser: Google Chrome
 - Version: 120.0.6099.130

**Comment by Nonononoki** [comment]
This ia expected behaviour. Incompatible users will be removed in a future update.
