### ISSUE TITLE
[BUG] search results jump back after sending a compliment

### ISSUE THREAD

**Issue by nthxznthxz** [Alovoa/alovoa#351]
is this a "just me" issue?

probably needs a "swipe history" to replicate this
enter the search mode, click on a profile to see more, click the heart & send a compliment

now the previous seven (7) swiped profiles reappear, meaning a need to re-swipe seven (7) already swiped profiles

**Comment by nthxznthxz** [comment]
okay the number of past swipes on top of swipe stack changes - from between half a dozen to a dozen

**Comment by nthxznthxz** [comment]
this also occurs upon
· loading in more profiles, like you've swiped and it loads then more profiles appear: that moment.
· clicking the cross/not interest button while seeing a full profile

**Comment by Nonononoki** [comment]
Wrong repo, please post the bug report here: https://github.com/Alovoa/alovoa-expo
