### ISSUE TITLE
[FEATURE] Raise "Something about myself" char limit from 200 to 100_000

### ISSUE THREAD

**Issue by Veraellyunjie** [Alovoa/alovoa#361]
Actually, [this.](https://github.com/Alovoa/alovoa/issues/280)
Yet it takes development effort so we can't expect those implemented promptly.

Right now, "Something about myself" freeform text field is limited to 200 characters.
The issue linked above mentions 250 characters, so it has deteriorated.
200 characters is +- 5 lines of text.

A draft txt I have written for my Alovoa profile is 108 lines and 2959 chars,
with some parts still missing, so you can double the estimate,
and I'd write in 2 languages since English isn't my native one,
so you can double the estimate again.
My description needs 12_000 characters. Subject to growth over time.

Raising char limit, I believe, is easy and quick to implement.

---

An additional note, "Something about myself" should be richer than txt.
Hyperlinks at least. E.g. I'd like to link some songs that I feel are descriptive of me.
Alovoa should recognize links and render them as clickable/tappable

**Comment by Nonononoki** [comment]
- Allowing links in profile is a huge security risk
- Long texts break the UI
- Long texts are much harder to moderate
- You're not doing yourself a favor with a long essay, save it for after a match.

I'm also currently working on profile prompts, which give you 6x120 more characters to work with.

**Comment by Veraellyunjie** [comment]
> Allowing links in profile is a huge security risk

* Could you please elaborate? With examples.
* A link is just a text mark-up, and it is client web browser that handles opening it, not Alovoa. So what is Alovoa's business?
* On the tech side, Alovoa UI is orders of magnitude more complex than links, requiring only certain capable of rendering Alovoa "modern" web browsers which are further orders of magnitude more complex, which poses indescribably worse security risk than links.
* Forbidding hyperlinks in hyperlink web is ridiculous IMHO.
* Alovoa has gone an extra mile to detect links and forbid them. For now, it breaks user experience. OTOH, Alovoa could extend this mechanism to detecting "good" links (allow) vs "bad" links (forbid) vs "need moderation" links (moderate).

---

> Allowing links in profile is a huge security risk

> Long texts are much harder to moderate

If texts are moderated, then links would be moderated as well, wouldn't they?
Why not allow moderated links?

---

> Long texts are much harder to moderate

* Most users keep their description short, no matter how liberal char limit is. Only a fraction of people prefer long descriptions. So, not much larger volume to moderate.
* A `[Report]` button for crowd moderation might do better job of moderation - even with long texts and links - than centralized moderation.

---

> Long texts break the UI

* It is the UI that should adapt to content, not vice versa
* Let's allow long texts and open an issue of "Long texts break the UI" which will be fixed eventually

---

> You're not doing yourself a favor with a long essay, save it for after a match.

* I wouldn't call 6_000 chars a long writing when it comes to describing a person.
* For a match to take place, you need some sufficient data to build a match upon.
Without data no match that deserves attention can occur.
* From my personal experience, I won't even consider a candidate thing/person without knowing enough about them.

**Comment by Nonononoki** [comment]
> > Allowing links in profile is a huge security risk
> 
>     * Could you please elaborate? With examples.
> 
>     * A link is just a text mark-up, and it is client web browser that handles opening it, not Alovoa. So what is Alovoa's business?
> 
>     * On the tech side, Alovoa UI is orders of magnitude more complex than links, requiring only certain capable of rendering Alovoa "modern" web browsers which are further orders of magnitude more complex, which poses indescribably worse security risk than links.
> 
>     * Forbidding hyperlinks in hyperlink web is ridiculous IMHO.
> 
>     * Alovoa has gone an extra mile to detect links and forbid them. For now, it breaks user experience. OTOH, Alovoa could extend this mechanism to detecting "good" links (allow) vs "bad" links (forbid) vs "need moderation" links (moderate).
> 
> 
> > Allowing links in profile is a huge security risk
> 
> > Long texts are much harder to moderate
> 
>     * If texts are moderated, then links would be moderated as well, wouldn't they? Why not allow moderated links?
> 
>     * Such restrictions force me to either leave Alovoa as a not serious platform, or put my description on another website and just put into my description `Due to Alovoa text size restrictions, read about me at example com mypage`
> 
> 
> > Long texts are much harder to moderate
> 
>     * Most users keep their description short, no matter how liberal char limit is. Only a fraction of people prefer long descriptions. So, not much larger volume to moderate.
> 
>     * A `[Report]` button for crowd moderation might do better job of moderation - even with long texts and links - than centralized moderation.
> 
> 
> > Long texts break the UI
> 
>     * It is the UI that should adapt to content, not vice versa
> 
>     * Let's allow long texts and open an issue of "Long texts break the UI" which will be fixed eventually
> 
> 
> > You're not doing yourself a favor with a long essay, save it for after a match.
> 
>     * I wouldn't call 6_000 chars a long writing when it comes to describing a person.
> 
>     * For a match to take place, you need some sufficient data to build a match upon.
>       Without data no match that deserves attention can occur.
> 
>     * From my personal experience, I won't even consider a candidate thing/person without knowing enough about them.

1. Malware and phishing sites exist (https://support.mozilla.org/en-US/kb/how-does-phishing-and-malware-protection-work). URL can be hidden with a link shortening service.
2. Moderating links is so much more complicated than moderating text. I may reconsider my view if you can show me another dating platform that allows hyperlinks in the bio.
3. It IS about the reporting functionality. If a user reports another, the moderator obviously need to beck their public profile, which could contain a long bio with content that violates the ToS. A short bio of 200 chars can be moderated within seconds.
4. Breaking the UI could also mean that I need to scroll too much to read what's BELOW the bio, which could only be fixed by reducing the character limit of the bio. What solution do you have for this issue?
5. It's more or less the current standard. That's why most dating platforms also limit the bio length to max 300 chars or less.

**Comment by Veraellyunjie** [comment]
> 1. Malware and phishing sites exist (https://support.mozilla.org/en-US/kb/how-does-phishing-and-malware-protection-work). URL can be hidden with a link shortening service.

* It is responsibility of the user to check resources they visit.
* Suggestions by a browser can sometimes be helpful. But rather not. I find them intrusive and riddled with false-positives.
As a special case, e.g. Google and Facebook exactly match Mozilla's definition of malware as `software designed to infect your computer without your knowledge. Malware is most often used to steal personal information`, but these are never reported as malware.
So I disable such checks. My personal preference, YMMV.
For those who want to be "protected" by big abusers against small abusers, "modern" browsers have the feature built-in.
* By no means it is responsibility of Alovoa, so I would suggest just dropping the concern.

> 2. Moderating links is so much more complicated than moderating text. I may reconsider my view if you can show me another dating platform that allows hyperlinks in the bio.

> 5. It's more or less the current standard. That's why most dating platforms also limit the bio length to max 300 chars or less.

* Alovoa is the 1st dating platform I tried, I have no idea how others work. If others work the same way, then dating platforms are utter garbage not worth time and effort.
And if it really is this way, your comment - by revealing it - can save me ample time to try other approaches than dating platforms. Thank you.

* Comparing to others, Alovoa is FLOSS, and FLOSS is different.
One of features common in FLOSS - and I love it - is that a user isn't arbitrarily restricted, which is a widespread issue in non-FLOSS.

> 2. links

* E.g. on my local advertisements website, which is also moderated, you can't indeed put a clickable link like https://example.com/some-page but you can put an unclickable link like `example.com/some-page`, which is better than what I can do in Alovoa: `example com some-page`.
Still, I have never encountered abusive links on that ads site whereas good links to official product description page have to be copy-pasted instead of clicking on them. Annoying. This is real abuse.

* On other platforms like forums or video hosting sites that allow comments, user-posted links are good legit links in 99.999% of cases and contribute greatly to content quality.

> 5. bio length to max 300 chars or less

* 300 chars is 1.5 times better than 200 but is still way below the minimum to give a reasonable description to anything.
* If you still insist, then it would be fair if Alovoa itself limited its description to the same 200 chars, but I count 1290 chars of Alovoa description on https://alovoa.com/ and I find the description quite minimal.
Note that a person is a more complex construct and needs more description than a website.

> 3. It IS about the reporting functionality. If a user reports another, the moderator obviously need to beck their public profile, which could contain a long bio with content that violates the ToS. A short bio of 200 chars can be moderated within seconds.

* It would be even easier to just not run a dating platform. 0 seconds to moderate.
* Again, only a fraction of users write long bios. Most don't bother, even if you encourage them to. So average bio length will hardly soar. 
* Some projects implement community moderators - certain willing and trusted users get moderation privilege. They review reports and take action. It might offload part of the burden from Alovoa team.

> 4. Breaking the UI could also mean that I need to scroll too much to read what's BELOW the bio, which could only be fixed by reducing the character limit of the bio. What solution do you have for this issue?

1. At the top of the page - Table of Contents with links to sections anchors
2. Floating/pop-up buttons "scroll to TOC", "scroll to prev section" and "scroll to next section".

3. Alternatively - spoiler/see more/load more/continue reading
