### ISSUE TITLE
[FEATURE] Waive number of interests limit (or raise it)

### ISSUE THREAD

**Issue by Veraellyunjie** [Alovoa/alovoa#363]
Current limit of 5 is definitely not enough for me.

Why is there a limit on number of interests in the 1st place?

One can't presume that a certain number of interests is enough.

I would imagine interests are self-regulating - users who specify too much will get too much noise and will delete some of their interests themselves.

What if Alice and Bob share the same 10 interests, somewhat equally significant to both,
but given limit of 5, Alice specified interests 1..5 whereas Bob interests 6..10.
Alovoa will not match them.

If a user picks too many, Alovoa might show a warning like "You might wish to concentrate on the most prominent interests leaving less significant ones out".

**Comment by Nonononoki** [comment]
Increased the number of interests to 10, can be tested on beta.alovoa.com 41381f337e273766bda2eb575612348434817a10
