### ISSUE TITLE
[BUG] Login conflict w/ M3U8 Video Detector and Downloader userscript

### ISSUE THREAD

**Issue by Veraellyunjie** [Alovoa/alovoa#364]
[M3U8 Video Detector and Downloader](https://greasyfork.org/en/scripts/449581-m3u8%E8%A7%86%E9%A2%91%E4%BE%A6%E6%B5%8B%E4%B8%8B%E8%BD%BD%E5%99%A8-%E8%87%AA%E5%8A%A8%E5%97%85%E6%8E%A2
)

Installed via [Greasemonkey](https://addons.mozilla.org/en-US/firefox/addon/greasemonkey/) in desktop FireFox 119.0

Upon pressing `Sign in` button on https://app.alovoa.com/
When M3U8 userscript is disabled, captcha is presented -> correct filling -> log in
When M3U8 userscript is enabled, nothing happens -> no log in

I haven't tried other platforms/browsers/userscript managers with M3U8.

---

I've left [a comment](https://greasyfork.org/en/scripts/449581-m3u8%E8%A7%86%E9%A2%91%E4%BE%A6%E6%B5%8B%E4%B8%8B%E8%BD%BD%E5%99%A8-%E8%87%AA%E5%8A%A8%E5%97%85%E6%8E%A2/discussions/230790) about the issue at M3U8 userscript comment page

**Comment by Nonononoki** [comment]
Sorry, weird behaviour with browser addons are not supported. If it works without the add-on then you need to post a bug on their bugtracker.

**Comment by Veraellyunjie** [comment]
I understand your stance - you can't foretell behavior of any given 3rd-party software.
Yet it doesn't mean it should be discarded.

The issue is there is no bugtracker for M3U8 Video Detector and Downloader.
So neither of 2 projects will ever resolve it.
Bugs accumulate and no one wants to fix them or even knows how to do it.

If I were the M3U8 maintainer I might dare say that IMHO websites that use heavy customization via heavy js are hard to predict, don't lend themselves to interoperability, provide no reasonable way to fix and should even be avoided if possible.

Alovoa [js](https://app.alovoa.com/bundles/web-f3b9718d6d6da1a4784d36af710eeb7e.js) file is unhealthy 3.4 MB.
Perhaps debloating Alovoa UI may be a path to consider for better user experience, wider browser support, ease of maintenance and better interoperability.
