### ISSUE TITLE
[BUG] Edits to "Something about myself" not saved

### ISSUE THREAD

**Issue by Veraellyunjie** [Alovoa/alovoa#366]
I put my description in "Something about myself",
I see no "Save" button, so I assume it saves automatically.

I press "<-" (back) button,
get to user front page,
then again press "Edit profile".
My "Something about myself" edits are there.

But, I open app.alovoa.com in another tab or I visit it later,
my edits are gone - I see my previous text, not the last one.

It seems to happen when I try to put a hyperlink there.
Even when I omit `https://` part and even when I replace slashes with spaces.

No warning is presented.
Are links forbidden? Why?

BTW, the link I tried to put is `https://github.com/Alovoa/alovoa/issues/361`.
Have managed to save it as `github com Alovoa alovoa issues 361`

**Comment by Nonononoki** [comment]
Yeah, that's intended. No links allowed ;) Saving works fine otherwise

**Comment by Veraellyunjie** [comment]
1. Forbidding links is conceptually wrong
2. There should be a notice what is not accepted
3. There should be a warning about unacceptable content instead of just dropping user edits
