### ISSUE TITLE
[BUG] Only 5 interests can be seen without using scrollbar

### ISSUE THREAD

**Issue by Veraellyunjie** [Alovoa/alovoa#374]
> Increased the number of interests to 10, can be tested on beta.alovoa.com
https://github.com/Alovoa/alovoa/issues/363#issuecomment-1987145834

Desktop browser.
"Interests" pop-up window occupies about half of height.
Upon adding 6th, 7th etc. interest, the pop-up keeps its size, I can see 5 interests and a scrollbar. Scrollbar works.
Given there is unused vertical space, I'd expect more (all?) interests seen at a glance.

**Comment by Nonononoki** [comment]
Please post UI bugs regarding app.alovoa.com and native apps to the correct repo instead: https://github.com/Alovoa/alovoa-expo/issues
