### ISSUE TITLE
[BUG] truncated "Something about myself"

### ISSUE THREAD

**Issue by Veraellyunjie** [Alovoa/alovoa#376]
Filled 245 / 255 characters in "Something about myself" on desktop.
Open "Edit profile" in mobile app - it shows 245 / 200 at the bottom right corner and the text itself is incomplete.

**Comment by Nonononoki** [comment]
Please post UI bugs regarding app.alovoa.com and native apps to the correct repo instead: https://github.com/Alovoa/alovoa-expo/issues
