### ISSUE TITLE
[FEATURE] multiple persons at a glance in Search

### ISSUE THREAD

**Issue by Veraellyunjie** [Alovoa/alovoa#381]
One-by-one approach is inefficient.
When I have to go through lots of photos on my PC, I don't open them in a viewer one-by-one. I use huge thumbnails so I can see about 20 pics simultaneously. Huge boost to productivity.
Similarly, a web search engine doesn't present results one-by-one but lists several on a page with more pages available.
Current mode might be OK for small screens, but as soon as you open Alovoa on a tablet or a desktop, it feels hampered.

**Comment by Nonononoki** [comment]
Please post UI bugs regarding app.alovoa.com and native apps to the correct repo instead: https://github.com/Alovoa/alovoa-expo/issues
