### ISSUE TITLE
[FEATURE] Go to next person without (dis)liking current one

### ISSUE THREAD

**Issue by Veraellyunjie** [Alovoa/alovoa#382]
[Multiple profiles shown at Search](https://github.com/Alovoa/alovoa/issues/381) would be even better,
whereas for one-by-one mode please make it possible to skip liking/disliking and still see new faces.
Sometimes you don't feel like disliking/blocking them but liking would be too much. You need additional time to consider a person.

Also bookmarking https://github.com/Alovoa/alovoa/issues/369

**Comment by Nonononoki** [comment]
Please post UI bugs regarding app.alovoa.com and native apps to the correct repo instead: https://github.com/Alovoa/alovoa-expo/issues

**Comment by Veraellyunjie** [comment]
OK, but I wonder whether it is purely UI feature.
IIUIC, back end needs to understand skipping without (dis)liking as well - to not repeat previous faces on your next session...
