### ISSUE TITLE
[BUG] Undoable "dislike" - implemented in 2021. Where is it in 2024?

### ISSUE THREAD

**Issue by Veraellyunjie** [Alovoa/alovoa#383]
https://github.com/Alovoa/alovoa/issues/91#issuecomment-885198517
> A list of disliked users can be shown via link in profile. You must like the user to remove the "dislike" status.

Has the feature been dropped? I can't find any link in profile to see a list of disliked users.

Also, "like disliked" isn't the same as "undo dislike" and either of them should be available

**Comment by Nonononoki** [comment]
It's actually been moved to "Likes". I really need a better name for this. Or should I put links in Profile instead?

**Comment by Veraellyunjie** [comment]
I have done quite a bit of "Dislikes" but none are displayed at "Likes" tab

**Comment by Nonononoki** [comment]
It's hidden in the three dots menu in the upper right, under "hidden users"

**Comment by Veraellyunjie** [comment]
Which is another bug that I procrastinated to report
Here it is: https://github.com/Alovoa/alovoa-expo/issues/49

**Comment by Nonononoki** [comment]
Closing issue because there's no need to undo a dislike, as you can still see the dislike in the Likes submenu and just like them
