### ISSUE TITLE
[BUG] misleading description in bug report form

### ISSUE THREAD

**Issue by Veraellyunjie** [Alovoa/alovoa#384]
New issue -> Bug report -> Get started

User is greeted with:
```
** Check if you're in the correct repository **
This repository only covers bugs in the backend and web UI of alovoa.com only.
```
again:
> **and web UI of alovoa.com only**

But my bug reports on UI have been closed with:
> Please post UI bugs regarding app.alovoa.com and native apps to the correct repo instead: https://github.com/Alovoa/alovoa-expo/issues

My reading of "web UI of alovoa.com" also includes "app.alovoa.com", and since "native" apps are effectively web browsers, they are also included.

Please clarify what goes where and add correct link https://github.com/Alovoa/alovoa-expo/issues to the description

**Comment by Nonononoki** [comment]
Done 4e8a913a7b142a6ee8a2466c21070dd590bdad78
