### ISSUE TITLE
[BUG] Getting HTTP Error 409 when at search tab

### ISSUE THREAD

**Issue by NRTICN** [Alovoa/alovoa#387]
** Check if you're in the correct repository **
This repository only covers bugs in the backend and web UI of alovoa.com only.

The request at following URL returns 409

https://alovoa.com/api/v1/search/users/$latitude/$longitude/50/4

**Describe the bug**

Search is not working.

**To Reproduce**
1. Go to 'Search' tab

**Expected behavior**

Search should show some profiles, or some message is no matches

**Screenshots**

<img width="1066" alt="Screenshot 2024-03-16 at 23 06 24" src="https://github.com/Alovoa/alovoa/assets/50528161/7641bb9e-4220-4f9f-94b5-7cd705106896">

**Desktop (please complete the following information):**
 - OS: macOS 14.4
 - Browser Firefox
 - Version  123.0
 - User Agent: `Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:123.0) Gecko/20100101 Firefox/123.0`

**Smartphone (please complete the following information):**
 - Device: OnePlus 11
 - OS: Android 13
 - Browser Chrome

**Additional context**

**Comment by Veraellyunjie** [comment]
https://github.com/Alovoa/alovoa/issues/375
https://github.com/Alovoa/alovoa-expo/issues/46
but I didn't know how to find error origin
@NRTICN thanks, you nailed it

**Comment by Nonononoki** [comment]
Seems like the typical random NPE - Added a few checks if the user is null. Could you try again?

**Comment by NRTICN** [comment]
> Seems like the typical random NPE - Added a few checks if the user is null. Could you try again?

Received following response of 170 bytes:

    Cannot invoke&quot;com.nonononoki.alovoa.entity.User.getId()&quot;because the return value of&quot;com.nonononoki.alovoa.entity.user.UserLike.getUserTo()&quot;is null

**Comment by Nonononoki** [comment]
> Yes, error didn't change. NPE in dating sounds too real though

Can you replicate this issue in beta.alovoa.com?

**Comment by Nonononoki** [comment]
Added a bunch of more null checks 6eef78f6d4c4471502b7c7a115a7e82b04064581, should work now :)

**Comment by Nonononoki** [comment]
Added a bunch of more null checks 6eef78f6d4c4471502b7c7a115a7e82b04064581, should work now :)

**Comment by NRTICN** [comment]
Indeed, works fine for me now.

Thanks!
