### ISSUE TITLE
[FEATURE] Purge non-confirmed users periodically

### ISSUE THREAD

**Issue by Nonononoki** [Alovoa/alovoa#390]
Requirements:
- Add new method in ScheduleService to purge non-confirmed users that haven't confirmed their email-address for 14 days
- Add new method to scheduleLong()
- The 14 days should be configurable in application.properties
- Add unit tests to ScheduleServiceTest

**Comment by lucifercr07** [comment]
@Nonononoki shall I pick this? The other issue assigned earlier i.e https://github.com/Alovoa/alovoa/issues/348 doesn't seem to be occurring anymore.
Once assigned can create a draft on steps to implement and share before implementation. Please let me know your thoughts.

**Comment by Nonononoki** [comment]
@lucifercr07 Sure, thabjs :)

**Comment by lucifercr07** [comment]
@Nonononoki shall we close this issue now?

**Comment by Nonononoki** [comment]
Yes
