### ISSUE TITLE
[BUG] no e-mail notification on chat messages

### ISSUE THREAD

**Issue by Veraellyunjie** [Alovoa/alovoa#396]
In profile settings:
```
Receive e-mails on likes and matches
Receive e-mails on chats
```
both have been ticked.

I got an e-mail on a match
but I also got chat messages but no e-mail about them

**Comment by Nonononoki** [comment]
1. Issue with swapped names should now be fixed: d871d0ca2251d0a726a9af4407f28b66507bcb6b
2. Not sure how to handle the email per message problem. A timeout of 1 hour is pretty long. My suggesion:
- Only send an email when the last message is NOT from the sender. In this case you only get one email if the sender sends 100 messages after another.
- Only send an email when the user hasn't been online recently. If the user has been online for X seconds don't send an email.

**Comment by lucifercr07** [comment]
@Nonononoki would like to work on this, let me know if there's any other issue of higher priority you would like me to pick up.

**Comment by Nonononoki** [comment]
@lucifercr07 Sure, thanks! :)

Requirements:
- Do NOT send a chat email if the previous message is less than an hour ago.
- Threshold is configurable in application.properties (app.mail.chat.min-threshold).

Hints:
- Do it in MessageService
- Don't forget unit tests

**Comment by Nonononoki** [comment]
@lucifercr07 Any progress on this topic? Otherwise I will start working on this.

**Comment by andresousadotpt** [comment]
@Nonononoki if @lucifercr07 don't want I would like to work on it :) (My first open-source contribution :D)

**Comment by lucifercr07** [comment]
@andresousadotpt please pick it up, have been busy with other projects wouldn't be able to work on this currently. Thanks.

**Comment by andresousadotpt** [comment]
I will be getting on this by friday :)

**Comment by Nonononoki** [comment]
@andresousadotpt I already did some work with this commit https://github.com/Alovoa/alovoa/commit/7fc36619d3ad61d6f37d7227e9e165f94ae446e2

**Comment by andresousadotpt** [comment]
Oh @Nonononoki then do you need help in other issues? You can keep working on this haha :)

**Comment by Nonononoki** [comment]
@andresousadotpt Added a new feature ticket #413, feel free to work on it :)

Closing this issue now.
