### ISSUE TITLE
[BUG] Unable to find matches

### ISSUE THREAD

**Issue by Dremor** [Alovoa/alovoa#406]
**Describe the bug**

The search page keep loading forever. The call to "https://alovoa.com/api/v1/search/users/" returns a 409 "Conflict" error.

**To Reproduce**

- Create a new account (due to https://github.com/Alovoa/alovoa/issues/405)
- Validate email and all other steps to setup a basic profile
- Try to search

**Expected behavior**

Possible matches appears.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser : Firefox
 - Version : 127

**Additional context**

Mobile app also impacted

**Comment by Nonononoki** [comment]
Updated the auth failure URL for app.alovoa.com ([e9f2066be6a52231d410ef7a0393cd5227071828](https://github.com/Alovoa/alovoa-expo/commit/e9f2066be6a52231d410ef7a0393cd5227071828)). Could you maybe try if it's still not working on the web app?

**Comment by Dremor** [comment]
Still nothing. I see the change in the console, so no cache or the like in the way.

Got an error in the 409 response : Cannot invoke &quot;com.nonononoki.alovoa.entity.User.getId()&quot; because the return value of &quot;com.nonononoki.alovoa.entity.user.UserLike.getUserTo()&quot; is null

**Comment by Nonononoki** [comment]
Should be working now after this commit c95e0416dcbac04645a8a33e37715608c038b133

**Comment by Dremor** [comment]
It does indeed. Thank you for tour work.
