### ISSUE TITLE
[BUG] Webapp return 503 error

### ISSUE THREAD

**Issue by Dremor** [Alovoa/alovoa#407]
**Describe the bug**

https://app.alovoa.com/ returns a 503 (service unavailable) error

**To Reproduce**

1. Visit https://app.alovoa.com/

**Expected behavior**

The webapps opens

**Screenshots**

![Copie d'écran_20240627_120604](https://github.com/Alovoa/alovoa/assets/1915939/3ac9da09-6acd-4ecf-acfd-f5cc911ddfee)

**Desktop (please complete the following information):**
 - OS: Fedora Kionite 40
 - Browser: Firefox
 - Version: 127.0.1 (64 bits)

**Additional context**
Mobile apps works fine

**Comment by Nonononoki** [comment]
Thanks for the heads up! Unfortunately, the server ran out of disk space. Removed some large logs but I'm thinking of upgrading the storage if this happens more frequenty.
