### ISSUE TITLE
[BUG] App unable to startup, possible CORS issues

### ISSUE THREAD

**Issue by Dremor** [Alovoa/alovoa#410]
**Describe the bug**

Cannot start app, it just keeps loading forever.

**To Reproduce**

1. Open https://app.alovoa.com/

**Expected behavior**

App loads.

**Screenshots**

![image](https://github.com/Alovoa/alovoa/assets/1915939/e053843d-2746-4b77-a863-ec700fcc3d32)

![image](https://github.com/Alovoa/alovoa/assets/1915939/8d142cae-f780-41d2-a4fe-f199a1aaa68e)

![image](https://github.com/Alovoa/alovoa/assets/1915939/8809f46a-f6fd-4bca-9e37-3337a0e57f6f)

**Desktop :**
 - OS: Windows
 - Browser : Firefox
 - Version : 128.0b9 (64 bits)

**Additional context**

Smartphone app also affected

**Comment by wiki-me** [comment]
Maybe this is related, but for me it shows this:

>Proxy Error
>The proxy server could not handle the request
>Reason: Error during SSL Handshake with remote server

**Comment by derkrasseleo** [comment]
> Maybe this is related, but for me it shows this:
> 
> > Proxy Error
> > The proxy server could not handle the request
> > Reason: Error during SSL Handshake with remote server

I get the same error

**Comment by Nonononoki** [comment]
Hi, the problem has been fixed now. Thanks for the report!
