### ISSUE TITLE
Are there apps for smartphones planned?

### ISSUE THREAD

**Issue by Glitchy-Tozier** [Alovoa/alovoa#48]

**Comment by Nonononoki** [comment]
No, but anyone can create one, the APIs are public (it's open-source, duh). Even if I were to create a mobile app, the stores (Google Play Store and Apple App Store) forbids donations that are not using they billing service. I could create a simple Android app and publish it to F-droid, but I don't like the idea of maintaining 2 code bases.

**Comment by Glitchy-Tozier** [comment]
I see, thank you for the reply!
