### ISSUE TITLE
Add 2-factor authentication

### ISSUE THREAD

**Issue by Nonononoki** [Alovoa/alovoa#49]
Not a priority since Google and FB OAuth already have that feature

**Comment by STPKITT** [comment]
Can Alovoa be used without having a Facebook or Google account then?

**Comment by Nonononoki** [comment]
@STPKITT Yes, but there's no 2FA when logging in with an email address for now

**Comment by STPKITT** [comment]
Allright, thanks very much!
If there will be another way of 2FA added to Alovoa I'd prefer that method, of which I don't know the name, in which you can use something like the app "Aegis".

**Comment by EchedeyLR** [comment]
An option could be setting up privacyIDEA against the userstore DB and performing MFA via de privacyIDEA API.

**Comment by ip6li** [comment]
2FA is easy to implement if using Keycloak as auth backend for Alovoa.

**Comment by Nonononoki** [comment]
Closed because of #314

**Comment by RokeJulianLockhart** [comment]
@Nonononoki, it shouldn't be. I can't auto-fill a code sent via e-mail. I can auto-fill a TOTP code generated from an OTPAuth URI.
