### ISSUE TITLE
Verification e-mail never arriving

### ISSUE THREAD

**Issue by mlovizio** [Alovoa/alovoa#51]
When trying to sign up to use Alovoa an error pops up in my browser as follow:

![brave_x9AcwpWPMM](https://user-images.githubusercontent.com/74993598/115792435-adbef580-a3a0-11eb-9494-a5ff3501af18.png)

The issue is that the account verification email never arrives, I´ve tried it with differents e-mail addresses with no luck.

**Comment by Nonononoki** [comment]
Thanks for testing and reporting the bug. Should be resolved now.
