### ISSUE TITLE
Potential Security Issue

### ISSUE THREAD

**Issue by JamieSlome** [Alovoa/alovoa#52]
Hello,

We recently received a vulnerability disclosure from @ibarrionuevo against your repository. I couldn't find a security policy or contactable e-mail to share the vulnerability details with you.

If you can provide me with an e-mail, I can send it over to you? Otherwise, you can view the advisory [here](https://huntr.dev/bounties/1-Alovoa/alovoa/).

It is private to only you and the discloser. If you have any questions, here to help!

-- Jamie from huntr.dev

**Comment by Nonononoki** [comment]
Should be fixed now by this commit: 76661ad253e371c876fe157200fc196c3f9667f3

**Comment by JamieSlome** [comment]
@Nonononoki - if you mark it as valid and confirm the patch on the platform, you will be rewarded the bounty, otherwise, I can sort this out on your behalf.

Let me know!
