### ISSUE TITLE
[Feature] Change password in profile 

### ISSUE THREAD

**Issue by heylix** [Alovoa/alovoa#59]

**Comment by Nonononoki** [comment]
Is this a feature request? Please provide more information.
Current way to change password is to reset in on the login page.

**Comment by Nonononoki** [comment]
Closing issue because reporter is not responding

**Comment by heylix** [comment]
Yes, this is a feature request. Usually, you can change your password from your settings or profile page. It's counterintuitive that alovoa only allows this via password reset, as there's the [principle of least surprise](https://en.wikipedia.org/wiki/Principle_of_least_astonishment), which states you shouldn't surprise the user.

For me, the password is a part of my account settings, so it should be possible to change the password there. In Github, for example, the password can be changed in Settings → Account security.

**Comment by Nonononoki** [comment]
Added in 6bad4ec11b7db59ed063065e2e0261506b681737
