### ISSUE TITLE
[UX] Date of birth picking difficulty (and range)

### ISSUE THREAD

**Issue by gnu1dea** [Alovoa/alovoa#65]
The date picker (on the registration page) was unhelpful: When I clicked the year to pick my birth year I was just presented with some options **without the possibility to go into the past/future**… I somehow ended up in 1909 and my options in the years section was in the 18xx range… I also couldn't just **set the date by manually writing one**.
Also, while potentially funny, is it desired to be able to pick a birthday in the 18xx?

That's an easy reason why - at the moment - I wouldn't recommend _Alovoa_ further: just picking a date is **really** frustrating and, if one doesn't give up, takes a **lot** of time.

**Comment by Nonononoki** [comment]
Hi @gnu1dea, 
I have removed the date picker library and instead chose to use the default one from the user's browser.
Hope you can recommend Alovoa now :)
