### ISSUE TITLE
feature request language

### ISSUE THREAD

**Issue by zen0bit** [Alovoa/alovoa#68]
i didnt dig in source code, but it will be posible to easy translate to another language?

**Comment by Nonononoki** [comment]
Hi!
Language files are located here: https://github.com/Alovoa/alovoa/tree/master/src/main/resources/i18n
Just create another message_LANG_ISO_CODE.message file and translate from the [English localozation file](https://github.com/Alovoa/alovoa/blob/master/src/main/resources/i18n/messages.properties)
It's very easy.
