### ISSUE TITLE
can´t open last profile

### ISSUE THREAD

**Issue by zen0bit** [Alovoa/alovoa#71]
I can´t open last profile from search result, or like and dislike, it is just moving with page.
[video](https://odysee.com/@oSoWoSo:a/alovoa:9)

Also can you keep everything in one tab?
So opened profile stays in same tab and back is working..

**Comment by Nonononoki** [comment]
Yes, I see the problem.

Opening everything in one tab is problematic, because the browser will "forget" the content of every previous tabs, forcing you to search again for example.

**Comment by Nonononoki** [comment]
Fixed with this commit: 9ac724db4a8db4ea36e3855d2864f50d49b1b1cb
