### ISSUE TITLE
Show liked/disliked people

### ISSUE THREAD

**Issue by zen0bit** [Alovoa/alovoa#74]
In profile yoou have option to show blocked people.
What about add same for liked and disliked people?
so you can easily track and change it...

**Comment by Nonononoki** [comment]
FYI, dislikes are only temporary, so it wouldn't make sense tracking it.
The numbers for blocks and reports are there so you can spot fake/inappropriate users much faster. What's the purpose of showing the number of likes?

**Comment by zen0bit** [comment]
Something like address book of people you like..

**Comment by Nonononoki** [comment]
Added liked users in profile in this commit 9f6e65f0d1e88b2257759cee532901069dd1a1d9
