### ISSUE TITLE
ActivityPub / Fediverse implementation

### ISSUE THREAD

**Issue by xplosionmind** [Alovoa/alovoa#75]
It would be great if anyone could install an Alovoa instance on their server and make it communicate with all of the other instances and the Fediverse.

**Comment by zen0bit** [comment]
Already here...
[ActivityPub support
enhancement
](https://github.com/Alovoa/alovoa/issues/13)

**Comment by xplosionmind** [comment]
My bad, I missed it.

Closing this issue since it is a duplicate of #13.
