### ISSUE TITLE
Error in searching for users

### ISSUE THREAD

**Issue by xplosionmind** [Alovoa/alovoa#77]
Correct me if I am wrong: the only way to find new people is by performing a search, starting from a selected location.

In my case, when I click on a part of the map, a magnifier icon appears; after clicking on it, too, I get a pop-up message saying:

> No compatible users in your area. Showing users all around the globe.

Nevertheless, only a female test user appears, and nobody else:

<img width="1440" alt="Screenshot 2021-06-20 at 8 10 31 AM" src="https://user-images.githubusercontent.com/42862428/122664019-3b934300-d18e-11eb-9844-81ad1264da38.png">

**Comment by xplosionmind** [comment]
I found out a possible reason: could it be possible that are going to appear only people who selected the same “I want…” field I did?

**Comment by Nonononoki** [comment]
Every user will eventually be displayed when you hide (or like, or block) the users showing in search and start a new search. Not really an issue because it's still a growing platform.

**Comment by xplosionmind** [comment]
Thanks for the feedback, but I cannot use the service at all if no user is displayed at all… Even when the range is <q>the whole world</q>!

**Comment by Nonononoki** [comment]
I'm not understanding your problem. For the above example, just click on the thumbs down button and new users will be loaded automatically.

**Comment by xplosionmind** [comment]
Ok, I now get it. I did not understand I should give thumbs up or down to refresh the results.

Thank you very much!

**Comment by Nonononoki** [comment]
This could be an UI/UX issue. Any idea to make it more obvious that the user should click on the thumbs up/down buttons?

**Comment by xplosionmind** [comment]
Probably, a simple info button specifying it would be enough
