### ISSUE TITLE
[Feature] Add remember me for email login

### ISSUE THREAD

**Issue by Nonononoki** [Alovoa/alovoa#78]

**Comment by Nonononoki** [comment]
Seems to be working nicely 5a815d37a0fc0a58800067cc7906e37764e4df66

**Comment by Nonononoki** [comment]
Okay, doesn't seem to be working for long, reopening issue. Could be because of the custom authentication method used.

**Comment by zen0bit** [comment]
Working for me..
signed up with email

**Comment by Nonononoki** [comment]
Ok, I give up. It really IS a problem if you don't use the default authentication method of Spring. Reverting previous changes (be22b0a33e4fef1d88cc87737b6740c3ce6b21f5).
The session timeout has been incresed from 30 minutes to 24 hours (c0bffcf46fbd50c8f47273585d8daefa94dad0a2). I think this is a nice compromise.
