### ISSUE TITLE
+part of email are stripped when registering

### ISSUE THREAD

**Issue by rhaamo** [Alovoa/alovoa#83]
Tried to register with something like `xxx+alovoa@domain.tld` and the whole `+alovoa` was stripped.

Looks like this part is triggered in the code https://github.com/Alovoa/alovoa/blob/master/src/main/java/com/nonononoki/alovoa/service/RegisterService.java#L112-L121

What's the goal of stripping that part ? And why only for PROD env ?

**Comment by Nonononoki** [comment]
It's to prevent spam. This way the user can only register once with an email address. Otherwise an email address can be used to create an infinite number of accounts by adding + and any string to the address.
Leaving this issue open to see if anyone thinks this is a big issue.

**Comment by Arteneko** [comment]
- Catchall e-mails
- e-mails using other characters as auto-sort rules
- e-mails provided as-is (with a + character)

There is no legitimate reason to break the standard e-mail format, and this won't prevent any form of spam.

**Comment by Nonononoki** [comment]
Should be fixed with this commit: 97baa1c50d50dce01fd19d1665210fb9db486acf
