### ISSUE TITLE
Is there a plan for JDK version changes?

### ISSUE THREAD

**Issue by EchedeyLR** [Alovoa/alovoa#89]
I have seen some projects around GitHub relying in normal  JDK versions instead of LTS ones.

I want to ask if this project is going to be likely the same or maintain a migration between LTS versions could be better for contributions in general and could avoid issues which could happen because of having to change JDK versions in short periods.

**Comment by Nonononoki** [comment]
OpenJDK is officially supported, and does not have an LTS version. As this is an open-source project, I try to avoid all closed-source dependencies, including the Oracle JDK.

**Comment by EchedeyLR** [comment]
OpenJDK 11 is LTS

**Comment by EchedeyLR** [comment]
OpenJDK 11 is the first LTS not endorsed at all by Oracle to be exact.

**Comment by EchedeyLR** [comment]
To be exact, you can use https://en.m.wikipedia.org/wiki/Java_version_history as a reilable source to know the support for third party OpenJDK builds and check the LTS ones including, but not limited to, the main OpenJDK project.

**Comment by Nonononoki** [comment]
@EchedeyLR The README.md states that OpenJDK 11 is officially supported (and also used in production), so I guess that should suffice?
> OpenJDK 11 is LTS 
Can I get a source for that? As far as I can tell OpenJDK has no LTS variant, only Java SE.

**Comment by EchedeyLR** [comment]
Yes, I read the current version supported. I just wanted to know how was going this to be addressed for future versions.

I think there is a misunderstanding here. OpenJDK is the official reference implementation for Java SE [since version 7](http://jdk.java.net/java-se-ri/7).

https://en.wikipedia.org/wiki/Java_version_history shows the support for Java 11 for extended support and marked as LTS (I think I don't need to point main source with this).

https://mail.openjdk.java.net/pipermail/jdk-dev/2018-August/001833.html as an explanation to what LTS means for OpenJDK.

An explanation to the versioning is in https://openjdk.java.net/jeps/322 too.

In the end, I don't know if I should point to a thread like https://stackoverflow.com/questions/52431764/difference-between-openjdk-and-adoptium-adoptopenjdk to understand the general process without having to fill this with a full article.

Maybe other useful links would be the current updates for OpenJDK 11: https://wiki.openjdk.java.net/display/JDKUpdates/JDK11u

**Comment by Nonononoki** [comment]
OpenJDK may be the official reference implementation for Java SE, but that doesn't mean that it's the same. The wikipedia page only mentions Java SE. The explanation of the LTS versioning is definitely informative, but there is not a single LTS version of OpenJDK 11 as far as I know.
But back to your question, there is no plan to officially support any other JDK version other than OpenJDK 11.

**Comment by EchedeyLR** [comment]
...

The third link points how OpenJDK team address Java versions marked as LTS.

**Comment by EchedeyLR** [comment]
Useful links:
- https://adoptopenjdk.net/
- https://adoptopenjdk.net/upstream.html

**Comment by Nonononoki** [comment]
I think most Linux distros use Oracle OpenJDK, which does not have LTS version according to wikipedia

**Comment by EchedeyLR** [comment]
All Red Hat distros use Red Hat own build which maintains also own patches ( https://access.redhat.com/articles/1299013 and https://access.redhat.com/products/openjdk ) towards https://openjdk.java.net/

However, Fedora seems to rely directly on upstream https://openjdk.java.net/ https://src.fedoraproject.org/rpms/java-11-openjdk

All Debian distros use OpenJDK source from OpenJDK project https://openjdk.java.net/ ( https://sources.debian.org/src/openjdk-11/11.0.11+9-1%7Edeb10u1/ )with the exception of Java Web Start and Java browser plugin which are provided by the Icedtea project. 

More info in the Debian Wiki page for OpenJDK and Java.

**Comment by Nonononoki** [comment]
I'm developing on Fedora and production runs on Debian, so no LTS

**Comment by EchedeyLR** [comment]
I use Debian/Devuan and main system too. I finished also vocational training of SysAdmin with this recently.

This is how I am telling you this. I also finished vocational training with this.

The releases of Debian OpenJDK are like that and you can check the wiki.

Other thing is that last LTS GA didn't arrive yet, is is in dot 11 in stable versions yet but dot 12 in unstable.

The links I shared can be checked easily. You also have Java Team of Debian with their Debian Salsa repository for builds.

**Comment by EchedeyLR** [comment]
Sorry for this. I should not be so insistent.

You already answered my question.
