### ISSUE TITLE
[Feature] Undoable "dislike"

### ISSUE THREAD

**Issue by gnu1dea** [Alovoa/alovoa#91]
I accidentally quickly disliked someone on the mobile website and noticed that there was no way to reverse it (or check whom exactly I disliked).
There's a "liked" list on the profile page; _maybe_ it'd be useful to have the same for "disliked"?

**Comment by Nonononoki** [comment]
Currently there is no way to undo dislikes and likes. What would undoing the dislike do? Unlike the "like" function, dislike does not affect the other user and only hides the user from your search.

**Comment by gnu1dea** [comment]
In my _accidental_ scenario it would be useful to undo it because there's no way to see whom I "disliked" after it happend: I can't check if I'd have "disliked" anyway, would have reserved my decision for later or even "liked" the person.
There could also be a _malicous_ scenario, where a friend quickly tabs on "dislike" while you're browsing, because "it was funny"… I dunno, I agree that there's not a strong case for it being undoable; however Tinder seems to provide a button (Rewind) for that + it's generally good UX design to be forgiving with consequential choices.

**Comment by Nonononoki** [comment]
Implemented: 500494ed64cb2d13100cf5dc152452c5d6934d5b
A list of disliked users can be shown via link in profile. You must like the user to remove the "dislike" status.

**Comment by gnu1dea** [comment]
OK, now: when I'm in the new "disliked" list and click a profile it shows this page:
"Whitelabel Error Page

This application has no explicit mapping for /error, so you are seeing this as a fallback.
Fri Jul 23 17:50:06 CEST 2021
There was an unexpected error (type=Not Found, status=404)."
I disliked someone new to test if it only shows an error for profiles that were "disliked" before this feature: it's still shows this error.

Thank you for the quick intial feature implementation though.

**Comment by Nonononoki** [comment]
Thanks, should be working now with this commit: 0b80187f3228463f4879b422225aad6c3396958d
