### ISSUE TITLE
Add country column to users when on search, show country flags on search and donate

### ISSUE THREAD

**Issue by Nonononoki** [Alovoa/alovoa#98]
Possible libraries:
https://mvnrepository.com/artifact/uk.recurse/reverse-country-code/1.0.0 (backend)
https://github.com/lipis/flag-icon-css (frontend)

**Comment by davidak** [comment]
Seeing the actual country and language would be useful.

**Comment by Nonononoki** [comment]
Added with this commit: 12232f165b0beb2336c872a345a2ee0f874ca37f
